"""CCOP 온톨로지 V4.8 — 정의 스펙 (전달본)

노드 25종 · 엣지 72종(활성 70, deprecated 2). 사이버범죄 수사 그래프 표준.
제공: 스카이월드와이드 · 기준 V4.8

외부 의존 0 — 표준 라이브러리조차 import 하지 않는 순수 선언이므로
파일 하나만 반입해 참조하거나 JSON 으로 덤프해 타 언어에서 쓸 수 있다.

당사 운영본(SoT)에서 외부에 필요한 정의만 추려 생성했다. 제외한 것과 이유:
  · EDGE_STYLE_V40 · VISUAL_STYLE_V40 · LAYOUT_PRESETS_V40
      → 당사 UI 렌더링 값(색·아이콘·레이아웃)
  · INVESTIGATION_WORKFLOWS_V40
      → 당사 UI 수사 시나리오 프리셋
  · LABEL_ALIASES
      → 당사 Text2Cypher 모델의 자연어 어휘 매핑
  · DOMAIN_USAGE
      → 당사 데이터 출처 정책(수사/OSINT/제공)
  · INFERENCE_RULES · INFERENCE_RULES_V37 · DERIVED_PROPERTY_REGISTRY
      → 추론·파생속성 로드맵. 대부분 미구현 상태라 구현 의무로 오해될 수 있어 제외
  · 메서드 14종
      → 당사 앱 헬퍼(프롬프트 생성·키워드 매칭 등). 아래 4개 함수로 대체

RELATIONSHIPS 항목에서 제외한 키:
  · semantic_relation — RDF식 camelCase 별칭(suspectIn 등). AgensGraph 는 미인용
      식별자를 소문자화하므로 엣지 라벨로 오인해 쓰면 깨진다.
  · source_types — 당사 CSV 파서가 참조하는 원본 컬럼쌍(내부 사정).
"""


class KICSCrimeDomainOntology:
    """온톨로지 V4.8 정의. 모든 속성은 순수 데이터이며 인스턴스화가 필요 없다."""

    # ── 4계층 구조 — 온톨로지 골격  (6종) ──
    LAYERS = {
        'Source': ['Source'],
        'Case': ['Case', 'Petition', 'PetitionCluster'],
        'Person': ['Person', 'Organization'],
        'Object': ['BankAccount',
                   'CryptoWallet',
                   'NetworkTrace',
                   'WebTrace',
                   'SiteCluster',
                   'FileTrace',
                   'DigitalID',
                   'Email',
                   'Phone',
                   'Vehicle',
                   'Device',
                   'ATM'],
        'Location': ['Location'],
        'Event': ['Transfer', 'Call', 'Access', 'Message', 'Movement', 'Impersonation'],
    }

    # ── 계층별 그래프 라벨 소속  (6종) ──
    LAYERS_GDB = {
        'Source': ['vt_src'],
        'Case': ['vt_case', 'vt_petition', 'pt_cluster'],
        'Person': ['vt_psn', 'vt_org'],
        'Object': ['vt_bacnt', 'vt_crypto', 'vt_ip', 'vt_site', 'site_cluster', 'vt_file', 'vt_id', 'vt_email', 'vt_telno', 'vt_vhcl', 'vt_dev', 'vt_atm'],
        'Location': ['vt_loc'],
        'Event': ['vt_transfer', 'vt_call', 'vt_access', 'vt_msg', 'vt_movement', 'vt_impersonation'],
    }

    # ── 노드 25종 — layer·properties(키)·attributes(전속성)·legal_category  (25종) ──
    ENTITIES = {
        'Source': {'layer': 'Source',
                   'label': 'vt_src',
                   'label_ko': '소스',
                   'properties': ['src_id', 'src_name', 'src_type', 'reliability_tier'],
                   'attributes': ['collector', 'collected_at', 'update_cycle', 'contact'],
                   'legal_category': '수사정보',
                   'description': '데이터 출처 (수집 기관/채널/신뢰 등급)'},
        'Case': {'layer': 'Case',
                 'label': 'vt_case',
                 'label_ko': '사건',
                 'properties': ['incdnt_no', 'flnm'],
                 'attributes': ['incdnt_nm',
                                'incdnt_typ_cd',
                                'crime_type',
                                'occrn_dt',
                                'damage_amount',
                                'case_summary',
                                'status',
                                'chrgdp_nm',
                                'chrg_plcmn_nm',
                                'police_station',
                                'source_id',
                                'rec_created'],
                 'role': 'anchor',
                 'legal_category': '수사사건',
                 'description': '수사 사건 케이스'},
        'Petition': {'layer': 'Case',
                     'label': 'vt_petition',
                     'label_ko': '진정서',
                     'properties': ['petition_id'],
                     'attributes': ['rcpt_dt',
                                    'rcpt_channel',
                                    'rcpt_station',
                                    'crime_type_cd',
                                    'damage_amt',
                                    'incdt_dt',
                                    'status',
                                    'linked_case_id',
                                    'preprocessed_by',
                                    'ocr_confidence',
                                    'schema_version',
                                    'raw_id',
                                    'source_id',
                                    'rec_created'],
                     'legal_category': '수사사건',
                     'description': '진정서/신고 (수사 개시 전·후 모두 존재)'},
        'PetitionCluster': {'layer': 'Case',
                            'label': 'pt_cluster',
                            'label_ko': '진정서군집',
                            'properties': ['cluster_id'],
                            'attributes': ['cluster_method',
                                           'crime_type_cd',
                                           'damage_amt_sum',
                                           'petition_cnt',
                                           'first_rcpt_dt',
                                           'last_rcpt_dt',
                                           'status',
                                           'source_id',
                                           'rec_created'],
                            'legal_category': '수사사건',
                            'description': '진정서 군집 허브 노드 — clusters_with O(n²) 엣지 대체 (v3.7)'},
        'Person': {'layer': 'Person',
                   'label': 'vt_psn',
                   'label_ko': '인물',
                   'properties': ['psn_id'],
                   'attributes': ['korn_flnm',
                                  'name',
                                  'dob',
                                  'gender',
                                  'nationality',
                                  'rrno_hash',
                                  'passport_no',
                                  'contact',
                                  'aliases',
                                  'risk_level',
                                  'occp_nm',
                                  'is_anonymous',
                                  'source_id',
                                  'rec_created',
                                  'verified',
                                  'confidence'],
                   'legal_category': '피의자정보',
                   'description': '인물 (피의자/피해자/참고인 — 역할은 엣지 타입으로; is_anonymous=True 시 성명불상)'},
        'Organization': {'layer': 'Person',
                         'label': 'vt_org',
                         'label_ko': '조직',
                         'properties': ['org_id'],
                         'attributes': ['org_name',
                                        'org_category',
                                        'inst_se_cd',
                                        'brno',
                                        'bank_cd',
                                        'addr',
                                        'member_count',
                                        'activity_type',
                                        'hierarchy_level',
                                        'source_id',
                                        'rec_created',
                                        'verified',
                                        'confidence'],
                         'legal_category': '피의자정보',
                         'description': '조직 (범죄단체 및 합법기관 통합, org_category로 분기)'},
        'BankAccount': {'layer': 'Object',
                        'sublayer': 'Financial',
                        'label': 'vt_bacnt',
                        'label_ko': '계좌',
                        'properties': ['account_no', 'bank_cd'],
                        'attributes': ['bank_nm',
                                       'dpstr_nm',
                                       'account_type',
                                       'bacnt_opn_dt',
                                       'inst_id',
                                       'is_burner',
                                       'is_frozen',
                                       'total_received',
                                       'total_sent',
                                       'transaction_cnt',
                                       'source_id',
                                       'rec_created',
                                       'verified',
                                       'confidence'],
                        'legal_category': '금융거래정보'},
        'CryptoWallet': {'layer': 'Object',
                         'sublayer': 'Financial',
                         'label': 'vt_crypto',
                         'label_ko': '가상자산',
                         'properties': ['wallet_addr', 'blockchain'],
                         'attributes': ['asset_type',
                                        'exchange',
                                        'balance',
                                        'risk_score',
                                        'kyc_verified',
                                        'tx_cnt',
                                        'source_id',
                                        'rec_created',
                                        'verified',
                                        'confidence'],
                         'legal_category': '가상자산거래정보'},
        'NetworkTrace': {'layer': 'Object',
                         'sublayer': 'Digital',
                         'label': 'vt_ip',
                         'label_ko': 'IP주소',
                         'properties': ['ip_addr'],
                         'attributes': ['version',
                                        'isp',
                                        'asn',
                                        'org',
                                        'country',
                                        'geo_region',
                                        'city',
                                        'is_vpn',
                                        'is_tor',
                                        'is_proxy',
                                        'is_hosting',
                                        'abuse_score',
                                        'source_id',
                                        'rec_created',
                                        'verified',
                                        'confidence'],
                         'legal_category': '통신자료'},
        'WebTrace': {'layer': 'Object',
                     'sublayer': 'Digital',
                     'label': 'vt_site',
                     'label_ko': '사이트',
                     'properties': ['url_addr'],
                     'attributes': ['dmn_addr',
                                    'site_type',
                                    'is_malicious',
                                    'risk_grd',
                                    'sign_kwrd',
                                    'detct_dt',
                                    'registrar',
                                    'whois_org',
                                    'reg_dt',
                                    'exp_dt',
                                    'page_title',
                                    'page_hash',
                                    'source_id',
                                    'rec_created',
                                    'verified',
                                    'confidence'],
                     'legal_category': '인터넷기록'},
        'SiteCluster': {'layer': 'Object',
                        'sublayer': 'Digital',
                        'label': 'site_cluster',
                        'label_ko': '피싱캠페인군집',
                        'properties': ['cluster_id'],
                        'attributes': ['html_fingerprint',
                                       'campaign_name',
                                       'cluster_method',
                                       'site_cnt',
                                       'ip_cnt',
                                       'first_seen',
                                       'last_seen',
                                       'source_id',
                                       'rec_created'],
                        'legal_category': '인터넷기록',
                        'description': '피싱 캠페인 군집 허브 노드 — HTML SimHash 지문으로 도메인/IP 교체 추적 (v3.7)'},
        'FileTrace': {'layer': 'Object',
                      'sublayer': 'Digital',
                      'label': 'vt_file',
                      'label_ko': '파일',
                      'properties': ['hash_val'],
                      'attributes': ['file_nm',
                                     'file_extsn_nm',
                                     'file_sz',
                                     'file_path',
                                     'creat_dt',
                                     'mdfr_dt',
                                     'is_malicious',
                                     'vt_score',
                                     'source_id',
                                     'rec_created',
                                     'verified',
                                     'confidence'],
                      'legal_category': '디지털증거'},
        'DigitalID': {'layer': 'Object',
                      'sublayer': 'Identity',
                      'label': 'vt_id',
                      'label_ko': '디지털ID',
                      'properties': ['id_val', 'platform'],
                      'attributes': ['id_type', 'profile_url', 'is_active', 'real_name', 'source_id', 'rec_created', 'verified', 'confidence'],
                      'legal_category': '신원정보',
                      'description': '플랫폼 계정 ID·닉네임 (vt_persona 흡수)'},
        'Email': {'layer': 'Object',
                  'sublayer': 'Digital',
                  'label': 'vt_email',
                  'label_ko': '이메일',
                  'properties': ['email_addr'],
                  'attributes': ['domain', 'provider', 'is_disposable', 'source_id', 'rec_created', 'verified', 'confidence'],
                  'legal_category': '통신자료'},
        'Phone': {'layer': 'Object',
                  'sublayer': 'Communication',
                  'label': 'vt_telno',
                  'label_ko': '전화번호',
                  'properties': ['telno'],
                  'attributes': ['country_code',
                                 'telco_nm',
                                 'join_typ_cd',
                                 'is_registered',
                                 'is_burner',
                                 'subs_holder',
                                 'imsi',
                                 'spam_cnt',
                                 'source_id',
                                 'rec_created',
                                 'verified',
                                 'confidence'],
                  'legal_category': '통신사실확인자료'},
        'Vehicle': {'layer': 'Object',
                    'sublayer': 'Physical',
                    'label': 'vt_vhcl',
                    'label_ko': '차량',
                    'properties': ['vhclno'],
                    'attributes': ['carmdl_nm',
                                   'carmdl_dtl_nm',
                                   'color',
                                   'ownr_nm',
                                   'rgst_dt',
                                   'stolen_yn',
                                   'source_id',
                                   'rec_created',
                                   'verified',
                                   'confidence'],
                    'legal_category': '차량정보',
                    'description': '차량 (번호판 기반 식별)'},
        'Device': {'layer': 'Object',
                   'sublayer': 'Digital',
                   'label': 'vt_dev',
                   'label_ko': '기기',
                   'properties': ['device_id'],
                   'attributes': ['dev_type', 'imei', 'mac_addr', 'model', 'os', 'os_version', 'source_id', 'rec_created', 'verified', 'confidence'],
                   'legal_category': '디지털증거',
                   'description': '기기 (스마트폰/PC/태블릿/불법중계기 등)'},
        'ATM': {'layer': 'Object',
                'sublayer': 'Physical',
                'label': 'vt_atm',
                'label_ko': 'ATM',
                'properties': ['atm_id'],
                'attributes': ['bank_nm', 'bank_cd', 'loc_id', 'address', 'is_outdoor', 'source_id', 'rec_created'],
                'legal_category': '물리증거'},
        'Location': {'layer': 'Location',
                     'label': 'vt_loc',
                     'label_ko': '위치',
                     'properties': ['loc_id'],
                     'attributes': ['loc_type',
                                    'address',
                                    'lat',
                                    'lng',
                                    'place_name',
                                    'sido_nm',
                                    'sigungu_nm',
                                    'bsst_nm',
                                    'bsst_addr',
                                    'telecom',
                                    'cctv_id',
                                    'cctv_operator',
                                    'source_id',
                                    'rec_created'],
                     'legal_category': '위치정보'},
        'Transfer': {'layer': 'Event',
                     'label': 'vt_transfer',
                     'label_ko': '이체',
                     'properties': ['event_id'],
                     'attributes': ['dlng_sn',
                                    'dlng_amt',
                                    'blnc_amt',
                                    'dlng_se_cd',
                                    'dlng_dt',
                                    'dlng_memo_cn',
                                    'trrc_psnnm',
                                    'atm_mng_no',
                                    'hop_level',
                                    'is_suspicious',
                                    'source_id',
                                    'rec_created',
                                    'verified',
                                    'confidence'],
                     'legal_category': '금융거래정보',
                     'description': '자금 이체 행위 (Bridge Key: dlng_sn → TB_FIN_BACNT_DLNG)'},
        'Call': {'layer': 'Event',
                 'label': 'vt_call',
                 'label_ko': '통화',
                 'properties': ['event_id'],
                 'attributes': ['call_sn',
                                'call_strt_dt',
                                'call_dur_sec',
                                'call_typ_cd',
                                'dsptch_telno',
                                'rcptn_telno',
                                'bsst_loc_id',
                                'source_id',
                                'rec_created',
                                'verified',
                                'confidence'],
                 'legal_category': '통신사실확인자료',
                 'description': '통화 기록 (Bridge Key: call_sn → TB_TELNO_CALL_DTL)'},
        'Access': {'layer': 'Event',
                   'label': 'vt_access',
                   'label_ko': '접속',
                   'properties': ['access_id'],
                   'attributes': ['lgn_sn',
                                  'user_id',
                                  'result_cd',
                                  'service_nm',
                                  'access_dt',
                                  'access_type',
                                  'action',
                                  'user_agent',
                                  'status_code',
                                  'bytes_sent',
                                  'bytes_recv',
                                  'source_id',
                                  'rec_created',
                                  'verified',
                                  'confidence'],
                   'access_subtypes': {'web': ['action', 'user_agent', 'status_code', 'bytes_sent', 'bytes_recv'], 'comm': [], 'banking': []},
                   'legal_category': '통신자료',
                   'description': '웹/네트워크 접속 행위 web/comm/banking (Bridge Key: lgn_sn → TB_SYS_LGN_EVT). R8: 노드분할 대신 access_type 속성으로 서브타입 표현(재학습 회피)'},
        'Message': {'layer': 'Event',
                    'label': 'vt_msg',
                    'label_ko': '메시지',
                    'properties': ['event_id'],
                    'attributes': ['msg_sn',
                                   'msg_type',
                                   'app_nm',
                                   'room_id',
                                   'dsptch_dt',
                                   'content_hash',
                                   'spam_yn',
                                   'mentions_account',
                                   'mentions_url',
                                   'sentiment_cd',
                                   'source_id',
                                   'rec_created',
                                   'verified',
                                   'confidence'],
                    'legal_category': '통신사실확인자료',
                    'description': '메시지 (SMS, 메신저 등) (Bridge Key: msg_sn → TB_TELNO_SMS_MSG / TB_CHAT_MSG)'},
        'Movement': {'layer': 'Event',
                     'label': 'vt_movement',
                     'label_ko': '이동이벤트',
                     'properties': ['mov_id'],
                     'attributes': ['mov_type',
                                    'timestamp',
                                    'loc_id',
                                    'vhclno',
                                    'cctv_id',
                                    'rcgn_sn',
                                    'telno',
                                    'evt_typ_nm',
                                    'loc_evt_sn',
                                    'card_no',
                                    'tk_pnm',
                                    'gf_pnm',
                                    'vhcl_no',
                                    'mv_sn',
                                    'imgr_se_cd',
                                    'flight_no',
                                    'port_nm',
                                    'imgr_sn',
                                    'source_id',
                                    'rec_created',
                                    'verified',
                                    'confidence'],
                     'legal_category': '위치정보',
                     'description': 'LPR·기지국·교통카드·출입국 이동이벤트 통합 노드 (vt_lpr_evt + vt_loc_evt 대체)'},
        'Impersonation': {'layer': 'Event',
                          'label': 'vt_impersonation',
                          'label_ko': '사칭이벤트',
                          'properties': ['event_id'],
                          'attributes': ['method', 'fake_name', 'script_type', 'start_dt', 'end_dt', 'source_id', 'rec_created', 'verified', 'confidence'],
                          'legal_category': '전기통신금융사기',
                          'description': '사칭 이벤트 노드 — V3.3에서 impersonates 엣지에서 승격 (전기통신금융사기법 제3조)'},
    }

    # ── 엣지 72종 — domain/range·properties·meaning·legal_significance  (72종) ──
    RELATIONSHIPS = {
        'suspect_in': {'domain': 'Person',
                       'range': 'Case',
                       'label_ko': '피의자',
                       'meaning': '인물이 사건의 피의자로 관련',
                       'legal_significance': '피의자정보',
                       'properties': ['confidence', 'verified', 'valid_from', 'source_id', 'rec_created']},
        'victim_in': {'domain': 'Person',
                      'range': 'Case',
                      'label_ko': '피해자',
                      'meaning': '인물이 사건의 피해자로 관련',
                      'legal_significance': '피해자정보',
                      'properties': ['damage_amount', 'valid_from', 'source_id', 'rec_created']},
        'witness_in': {'domain': 'Person',
                       'range': 'Case',
                       'label_ko': '참고인',
                       'meaning': '인물이 사건의 참고인으로 관련',
                       'legal_significance': '참고인진술',
                       'properties': ['statement_date', 'source_id', 'rec_created']},
        'same_as': {'domain': 'Person|DigitalID|Phone',
                    'range': 'Person|DigitalID|Phone',
                    'label_ko': '동일실체',
                    'meaning': '두 vt_psn 또는 vt_id가 동일 실체로 해소됨 (엔티티 해소; 유사 계정 pokpok1270↔pokpokpok1270 포함)',
                    'legal_significance': '신원확인',
                    'properties': ['match_score', 'match_basis', 'review_status', 'rec_created'],
                    'inferred': True},
        'contradicts': {'domain': 'Person',
                        'range': 'Person',
                        'label_ko': '모순정보',
                        'meaning': '두 vt_psn 정보가 모순됨 (명의도용 등)',
                        'legal_significance': '신원확인',
                        'properties': ['conflict_field', 'conflict_detail', 'rec_created'],
                        'inferred': True},
        'knows': {'domain': 'Person',
                  'range': 'Person',
                  'label_ko': '지인',
                  'meaning': '두 인물의 사회적 지인 관계 (고향친구/동창 등, 공범 미확정 — accomplice_of와 구분)',
                  'legal_significance': '관계정보',
                  'properties': ['relation_type', 'confidence', 'valid_from', 'source_id', 'rec_created']},
        'linked_id': {'domain': 'Object|NetworkTrace',
                      'range': 'DigitalID',
                      'label_ko': '식별자연결',
                      'meaning': '계좌·전화 등 객체에 연결된 온라인 식별자 (공인인증서 발급 ID / 포털 역조회 계정)',
                      'legal_significance': '신원확인',
                      'properties': ['link_basis', 'confidence', 'valid_from', 'source_id', 'rec_created']},
        'mentions_id': {'domain': 'Message',
                        'range': 'DigitalID',
                        'label_ko': '계정기재',
                        'meaning': '게시물/메시지에 기재된 온라인 계정 (광고글의 텔레그램 ID Zion7950 등)',
                        'legal_significance': '증거물',
                        'properties': ['confidence', 'source_id', 'rec_created']},
        'filed_as': {'domain': 'Petition',
                     'range': 'Case',
                     'label_ko': '사건전환',
                     'meaning': '진정서가 수사 사건으로 전환됨',
                     'legal_significance': '수사개시',
                     'properties': ['converted_dt', 'converted_by', 'source_id', 'rec_created']},
        'clusters_with': {'domain': 'Petition',
                          'range': 'Petition',
                          'label_ko': '유사진정서(deprecated)',
                          'meaning': '[DEPRECATED v3.7] 유사 진정서 군집 연결 — belongs_to_cluster 패턴으로 교체',
                          'legal_significance': None,
                          'properties': ['sim_score', 'cluster_id', 'rec_created'],
                          'inferred': True,
                          'deprecated': True,
                          'replaced_by': 'belongs_to_cluster'},
        'belongs_to_cluster': {'domain': 'Petition',
                               'range': 'PetitionCluster',
                               'label_ko': '군집소속',
                               'meaning': '진정서가 진정서군집(pt_cluster) 허브 노드에 소속됨 (v3.7)',
                               'legal_significance': None,
                               'properties': ['sim_score', 'rec_created'],
                               'inferred': True},
        'uses_id': {'domain': 'Person',
                    'range': 'DigitalID',
                    'label_ko': 'ID사용',
                    'meaning': '인물이 플랫폼 ID/닉네임을 사용',
                    'legal_significance': '신원확인',
                    'properties': ['platform', 'valid_from', 'valid_to', 'source_id', 'rec_created']},
        'uses_email': {'domain': 'Person',
                       'range': 'Email',
                       'label_ko': '이메일사용',
                       'meaning': '인물이 이메일 주소를 사용',
                       'legal_significance': '신원확인',
                       'properties': ['valid_from', 'valid_to', 'source_id', 'rec_created']},
        'drives': {'domain': 'Person',
                   'range': 'Vehicle',
                   'label_ko': '차량운행',
                   'meaning': '인물이 차량을 운행/소유',
                   'legal_significance': '차량정보',
                   'properties': ['valid_from', 'valid_to', 'source_id', 'rec_created']},
        'recorded_in': {'domain': 'Any', 'range': 'Movement', 'label_ko': '이동기록', 'meaning': '차량/전화번호가 이동이벤트에 기록됨', 'legal_significance': '위치정보'},
        'occurred_at': {'domain': 'Any', 'range': 'Location', 'label_ko': '발생위치', 'meaning': '이벤트의 발생 위치', 'legal_significance': '위치정보'},
        'owns': {'domain': 'Person',
                 'range': 'Any',
                 'label_ko': '소유',
                 'meaning': '인물이 객체를 소유함 (범용 — 구체 엣지 우선 사용)',
                 'legal_significance': '피의자정보',
                 'properties': ['start_date', 'end_date', 'verification_source']},
        'owns_phone': {'domain': 'Person',
                       'range': 'Phone',
                       'label_ko': '전화소유',
                       'meaning': '닉네임/인물이 전화번호를 소유함',
                       'legal_significance': '통신사실확인자료',
                       'properties': ['valid_from', 'valid_to', 'source_id', 'rec_created']},
        'has_account': {'domain': 'Person',
                        'range': 'BankAccount',
                        'label_ko': '계좌소유',
                        'meaning': '닉네임/인물이 계좌를 소유함',
                        'legal_significance': '금융거래정보',
                        'properties': ['valid_from', 'valid_to', 'source_id', 'rec_created']},
        'used_ip': {'domain': 'Person|Phone|DigitalID|Device|BankAccount',
                    'range': 'NetworkTrace',
                    'label_ko': 'IP사용',
                    'meaning': '닉네임/인물/계정/계좌(뱅킹 접속)가 IP 주소를 사용함. ※시각별 접속 레코드가 있는 소스는 R8 vt_access(banking)+access_via/accessed_from reification 우선, 요약 관계만 있으면 '
                               '본 엣지 직결',
                    'legal_significance': '디지털증거',
                    'properties': ['valid_from', 'valid_to', 'confidence', 'source_id', 'rec_created']},
        'linked_to': {'domain': 'Any', 'range': 'Any', 'label_ko': '연결됨', 'meaning': '두 증거가 연결됨', 'legal_significance': None},
        'transferred_to': {'domain': 'BankAccount',
                           'range': 'BankAccount|CryptoWallet',
                           'label_ko': '이체(다단계추론)',
                           'meaning': '다단계 자금 세탁 추론 엣지 — 직접 생성 금지, from/to_account Fan-out 이후 추론으로만 생성',
                           'legal_significance': '금융거래정보',
                           'properties': ['hop_level', 'first_dlng_dt', 'last_dlng_dt', 'txn_count', 'total_amount', 'time_basis', 'amount', 'transfer_date'],
                           'inferred': True,
                           'transitive': True,
                           'inference_confidence': 0.85},
        'registered_to': {'domain': 'Phone|DigitalID',
                          'range': 'Person',
                          'label_ko': '명의자',
                          'meaning': '전화번호/플랫폼 계정의 등록(실명확인) 명의자',
                          'legal_significance': '통신사실확인자료|가입자정보 제공요청(전기통신사업법 83조)',
                          'properties': ['valid_from', 'valid_to', 'source_id', 'rec_created']},
        'accomplice_of': {'domain': 'Person', 'range': 'Person', 'label_ko': '공범', 'meaning': '공범 관계', 'legal_significance': '피의자정보', 'inferred': True},
        'member_of': {'domain': 'Person',
                      'range': 'Organization',
                      'label_ko': '조직소속',
                      'meaning': '인물이 조직(범죄단체 포함)에 소속됨',
                      'legal_significance': '피의자정보',
                      'properties': ['role', 'valid_from', 'valid_to', 'source_id', 'rec_created']},
        'from_account': {'domain': 'BankAccount|CryptoWallet|ATM', 'range': 'Transfer', 'label_ko': '출금계좌', 'meaning': '이체의 출금 계좌', 'legal_significance': '금융거래정보'},
        'to_account': {'domain': 'Transfer', 'range': 'BankAccount|CryptoWallet|ATM', 'label_ko': '입금계좌', 'meaning': '이체의 입금 계좌', 'legal_significance': '금융거래정보'},
        'caller': {'domain': 'Phone', 'range': 'Call', 'label_ko': '발신', 'meaning': '통화의 발신 번호', 'legal_significance': '통신사실확인자료'},
        'callee': {'domain': 'Call', 'range': 'Phone', 'label_ko': '수신', 'meaning': '통화의 수신 번호', 'legal_significance': '통신사실확인자료'},
        'accessed_from': {'domain': 'Access', 'range': 'NetworkTrace', 'label_ko': '접속IP', 'meaning': '접속의 출발 IP', 'legal_significance': '통신자료'},
        'sent_msg': {'domain': 'Phone|DigitalID', 'range': 'Message', 'label_ko': '발신', 'meaning': '메시지 발신 번호', 'legal_significance': '통신사실확인자료'},
        'received_msg': {'domain': 'Message',
                         'range': 'Phone|DigitalID',
                         'label_ko': '수신번호',
                         'meaning': '메시지 수신 전화번호 (received_by의 Phone 버전)',
                         'legal_significance': '통신사실확인자료'},
        'access_via': {'domain': 'Access',
                       'range': 'Phone|DigitalID|BankAccount',
                       'label_ko': '접속수단',
                       'meaning': '접속 이벤트에 사용된 통신수단/계정/모바일뱅킹 (vt_access 주체 다형)',
                       'legal_significance': '통신자료',
                       'properties': ['valid_from', 'confidence', 'source_id', 'rec_created']},
        'via_ip': {'domain': 'Transfer',
                   'range': 'NetworkTrace',
                   'label_ko': '이체접속IP',
                   'meaning': '이체 이벤트의 접속 IP (모바일뱅킹 등)',
                   'legal_significance': '통신자료',
                   'properties': ['source_id', 'rec_created']},
        'mentions_location': {'domain': 'Message',
                              'range': 'Location',
                              'label_ko': '위치기재',
                              'meaning': '메시지/게시물에 언급된 장소 (거래 장소/은닉 좌표 등)',
                              'legal_significance': '증거물',
                              'properties': ['confidence', 'source_id', 'rec_created']},
        'sourced_from': {'domain': 'Any',
                         'range': 'Source',
                         'label_ko': '출처',
                         'meaning': '데이터 노드 → vt_src 역참조. tier 1~3만 엣지 생성, tier 4~5는 source_id 속성만 사용',
                         'legal_significance': '수사정보',
                         'properties': ['src_tier', 'rec_created']},
        'owns_vehicle': {'domain': 'Person',
                         'range': 'Vehicle',
                         'label_ko': '차량소유',
                         'meaning': '인물이 차량을 법적으로 소유함 (drives는 운행, owns_vehicle은 소유권)',
                         'legal_significance': '차량정보',
                         'properties': ['valid_from', 'valid_to', 'source_id', 'rec_created']},
        'related_case': {'domain': 'Case',
                         'range': 'Case',
                         'label_ko': '관련사건',
                         'meaning': '공유 증거(계좌/전화) 기반 사건 연결',
                         'inference': True,
                         'confidence': 0.75,
                         'legal_significance': '연쇄사건 추적'},
        'belongs_to': {'domain': 'BankAccount', 'range': 'Organization', 'label_ko': '소속기관', 'meaning': '계좌 소속 금융기관', 'legal_significance': '금융거래정보'},
        'works_at': {'domain': 'Person', 'range': 'Organization', 'label_ko': '소속', 'meaning': '인물의 소속 조직', 'legal_significance': '내부자 식별'},
        'represents': {'domain': 'Person',
                       'range': 'Organization',
                       'label_ko': '대표',
                       'meaning': '인물이 법인의 대표(대표이사/사내이사 등). 같은 대표의 다수 법인 탐지에 활용',
                       'legal_significance': '법인등기',
                       'properties': ['rprs_se_cd', 'valid_from', 'valid_to', 'source_id'],
                       'std_source': 'TB_INST_RPRSV_REL_T',
                       'std_columns': {'rprs_se_cd': 'RPRS_SE_CD', 'valid_from': 'VLD_BGNG_DT', 'valid_to': 'VLD_END_DT', 'source_id': 'SRC_ID'}},
        'resolves_to': {'domain': 'WebTrace',
                        'range': 'NetworkTrace',
                        'label_ko': 'DNS조회',
                        'meaning': '도메인이 IP 주소로 조회됨 (DNS A/AAAA 레코드)',
                        'inference': True,
                        'legal_significance': '네트워크 추적'},
        'mentions_account': {'domain': 'Message',
                             'range': 'BankAccount',
                             'label_ko': '계좌언급',
                             'meaning': '메시지 내 계좌번호 언급',
                             'inference': True,
                             'confidence': 0.85,
                             'legal_significance': '보이스피싱 핵심증거'},
        'used_for': {'domain': 'Any',
                     'range': 'Impersonation',
                     'label_ko': '사칭수단',
                     'meaning': '전화번호/계정/이메일/사이트가 사칭 이벤트의 수단으로 사용됨',
                     'legal_significance': '전기통신금융사기법 제3조'},
        'targets': {'domain': 'Impersonation',
                    'range': 'Organization',
                    'label_ko': '사칭대상',
                    'meaning': '사칭 이벤트의 타겟 기관 (사칭당한 기관)',
                    'legal_significance': '전기통신금융사기법 제3조'},
        'operates': {'domain': 'Person',
                     'range': 'Any',
                     'label_ko': '운영',
                     'meaning': '인물/조직이 플랫폼·채널·사이트를 운영함',
                     'legal_significance': '범죄사실',
                     'properties': ['valid_from', 'valid_to', 'role', 'source_id', 'rec_created']},
        'recruits': {'domain': 'Person',
                     'range': 'Person',
                     'label_ko': '모집',
                     'meaning': '인물이 다른 인물을 모집함 (대포통장·판매원·투자자 유인)',
                     'legal_significance': '피의자정보',
                     'properties': ['recruit_type', 'date', 'source_id', 'rec_created']},
        'blackmails': {'domain': 'Person',
                       'range': 'Person',
                       'label_ko': '협박',
                       'meaning': '인물이 다른 인물을 협박함 (몸캠피싱·랜섬웨어)',
                       'legal_significance': '협박죄 구성요건',
                       'properties': ['method', 'date', 'source_id', 'rec_created']},
        'hosts': {'domain': 'NetworkTrace',
                  'range': 'WebTrace',
                  'label_ko': '호스팅',
                  'meaning': '서버 IP가 사이트를 호스팅함 (인프라 추적)',
                  'legal_significance': '네트워크 추적',
                  'properties': ['port', 'detected_at', 'source_id', 'rec_created']},
        'contains_file': {'domain': 'Any',
                          'range': 'FileTrace',
                          'label_ko': '파일내장',
                          'meaning': '사이트·메시지·ID가 파일을 내장/배포함 (증거물)',
                          'legal_significance': '디지털증거',
                          'properties': ['file_role', 'detected_at', 'source_id', 'rec_created']},
        'used_in_device': {'domain': 'Phone',
                           'range': 'Device',
                           'label_ko': '기기내사용',
                           'meaning': '전화번호(유심)이 특정 기기(IMEI)에서 사용됨 — 동일 IMEI에 3개+ 전화번호 시 불법중계기 의심 (v3.7)',
                           'legal_significance': '통신사실확인자료',
                           'properties': ['first_seen', 'last_seen', 'source_id', 'rec_created']},
        'belongs_to_campaign': {'domain': 'WebTrace',
                                'range': 'SiteCluster',
                                'label_ko': '캠페인소속',
                                'meaning': '사이트가 피싱캠페인군집(site_cluster) 허브 노드에 소속됨 (v3.7)',
                                'legal_significance': '인터넷기록',
                                'properties': ['sim_score', 'detected_at', 'source_id', 'rec_created'],
                                'inferred': True},
        'eg_used_account': {'domain': 'Case',
                            'range': 'BankAccount',
                            'label_ko': '피해금 수령 계좌',
                            'meaning': '사건에서 증거로 사용된 계좌 (피해금 수령·이체 경로)',
                            'legal_significance': '금융거래정보',
                            'properties': ['valid_from', 'valid_to', 'source_id', 'rec_created']},
        'eg_used_phone': {'domain': 'Case',
                          'range': 'Phone',
                          'label_ko': '범죄 사용 전화번호',
                          'meaning': '사건에서 증거로 사용된 전화번호 (보이스피싱·연락 수단)',
                          'legal_significance': '통신사실확인자료',
                          'properties': ['valid_from', 'valid_to', 'source_id', 'rec_created']},
        'eg_used_ip': {'domain': 'Case',
                       'range': 'NetworkTrace',
                       'label_ko': '범죄 사용 IP',
                       'meaning': '사건에서 증거로 사용된 IP 주소 (접속·공격 출발지)',
                       'legal_significance': '통신자료',
                       'properties': ['valid_from', 'valid_to', 'source_id', 'rec_created']},
        'accessed_to': {'domain': 'Access',
                        'range': 'WebTrace|BankAccount|DigitalID',
                        'label_ko': '목적지',
                        'meaning': '접속이벤트의 목적지 사이트 (accessed_from과 쌍으로 사용)',
                        'legal_significance': '통신자료',
                        'properties': ['source_id', 'rec_created']},
        'involves': {'domain': 'Case',
                     'range': 'Person',
                     'label_ko': '사건관련',
                     'meaning': '사건에 관련된 인물 (역할 미상 시 suspect_in/victim_in/witness_in 대신 사용)',
                     'legal_significance': '사건관련성',
                     'properties': ['source_id', 'rec_created']},
        'communicated_with': {'domain': 'NetworkTrace',
                              'range': 'NetworkTrace',
                              'label_ko': 'IP통신',
                              'meaning': 'IP 간 직접 통신 이력',
                              'legal_significance': '통신사실확인자료',
                              'properties': ['source_id', 'rec_created']},
        'contacted': {'domain': 'Phone|DigitalID',
                      'range': 'Phone|DigitalID',
                      'label_ko': '연락관계',
                      'meaning': '전화번호/메신저 계정 간 통화·연락 관계 (vt_call·대화상대 목록의 요약 엣지 성격)',
                      'legal_significance': '통신사실확인자료|압수수색(메신저 대화내역)',
                      'properties': ['source_id', 'rec_created', 'channel']},
        'impersonates': {'domain': 'Person',
                         'range': 'Organization',
                         'label_ko': '사칭',
                         'meaning': '인물이 기관/조직을 사칭 (v3.3에서 vt_impersonation 노드로 승격 — 본 직접 엣지는 read-only 유지)',
                         'legal_significance': '사칭수법',
                         'properties': ['source_id', 'rec_created']},
        'owns_wallet': {'domain': 'Person',
                        'range': 'CryptoWallet',
                        'label_ko': '지갑소유',
                        'meaning': '인물이 가상자산 지갑을 소유',
                        'legal_significance': '재산관계',
                        'properties': ['valid_from', 'valid_to', 'source_id', 'rec_created']},
        'performed_by': {'domain': 'Any',
                         'range': 'Person|Phone|DigitalID|Device',
                         'label_ko': '수행주체',
                         'meaning': '접속(vt_access)·이동(vt_movement) 이벤트의 수행 주체 인물',
                         'legal_significance': '행위귀속',
                         'properties': ['source_id', 'rec_created']},
        'uses_device': {'domain': 'Person',
                        'range': 'Device',
                        'label_ko': '기기사용',
                        'meaning': '인물이 기기를 소유/사용',
                        'legal_significance': '디지털증거',
                        'properties': ['valid_from', 'valid_to', 'source_id', 'rec_created']},
        'verified_by': {'domain': 'Person',
                        'range': 'Person',
                        'label_ko': '검증자',
                        'meaning': '수사관(인물)이 대상 정보를 검증함 (Provenance 계열)',
                        'legal_significance': '증거검증',
                        'properties': ['verified_dt', 'source_id', 'rec_created']},
        'controls': {'domain': 'Person',
                     'range': 'BankAccount',
                     'label_ko': '실질지배',
                     'meaning': '인물이 계좌를 실질 지배(명의자와 무관한 실사용자) — 소유(has_account)와 구별',
                     'legal_significance': '실사용자',
                     'properties': ['confidence', 'source_id', 'rec_created']},
        'located_at': {'domain': 'Any',
                       'range': 'Location',
                       'label_ko': '위치',
                       'meaning': '고정 객체(ATM·기관 등)의 정적 위치 (이벤트 경유 occurred_at과 구별)',
                       'legal_significance': '위치정보',
                       'properties': ['source_id', 'rec_created']},
        'owns_device': {'domain': 'Person',
                        'range': 'Device',
                        'label_ko': '기기소유',
                        'meaning': '[DEPRECATED — uses_device 사용] 인물이 기기를 소유. 신규 데이터는 uses_device로 통일',
                        'legal_significance': '디지털증거',
                        'deprecated': True,
                        'alias_of': 'uses_device',
                        'properties': ['source_id', 'rec_created']},
        'sent_from_ip': {'domain': 'Message',
                         'range': 'NetworkTrace',
                         'label_ko': '발신IP',
                         'meaning': '메시지가 특정 IP에서 발신됨 — 착발신내역이 메시지+접속을 한 레코드로 제공(V4.5 G2)',
                         'legal_significance': '통신사실확인자료',
                         'properties': ['sent_at', 'source_id', 'rec_created']},
        'exchanged_to': {'domain': 'BankAccount',
                         'range': 'CryptoWallet',
                         'label_ko': '환전',
                         'meaning': '계좌 자금이 가상자산 지갑으로 환전됨 — 자금 종단 브리지(V4.5 G6)',
                         'legal_significance': '자금추적',
                         'properties': ['amount', 'exchanged_at', 'source_id', 'rec_created']},
        'linked_petition': {'domain': 'Petition',
                            'range': 'Case',
                            'label_ko': '진정연계',
                            'meaning': '진정서가 사건에 연계됨 — 기존 linked_to(Petition→Case) 대체(V4.5 R2)',
                            'legal_significance': '사건관리',
                            'properties': ['source_id', 'rec_created']},
        'eg_used_id': {'domain': 'Case',
                       'range': 'DigitalID',
                       'label_ko': '사건사용ID',
                       'meaning': '사건에서 사용·언급된 디지털ID(V4.5 R3 신설)',
                       'legal_significance': '수사대상',
                       'properties': ['source_id', 'rec_created']},
        'eg_used_email': {'domain': 'Case',
                          'range': 'Email',
                          'label_ko': '사건사용이메일',
                          'meaning': '사건에서 사용·언급된 이메일(V4.5 R3 신설)',
                          'legal_significance': '수사대상',
                          'properties': ['source_id', 'rec_created']},
    }

    # ── 개념명 → 그래프 라벨 (Person → vt_psn)  (25종) ──
    GDB_LABEL_MAP = {
        'Source': 'vt_src',
        'Case': 'vt_case',
        'Petition': 'vt_petition',
        'PetitionCluster': 'pt_cluster',
        'Person': 'vt_psn',
        'Organization': 'vt_org',
        'BankAccount': 'vt_bacnt',
        'CryptoWallet': 'vt_crypto',
        'NetworkTrace': 'vt_ip',
        'WebTrace': 'vt_site',
        'SiteCluster': 'site_cluster',
        'FileTrace': 'vt_file',
        'DigitalID': 'vt_id',
        'Email': 'vt_email',
        'Phone': 'vt_telno',
        'Vehicle': 'vt_vhcl',
        'Device': 'vt_dev',
        'ATM': 'vt_atm',
        'Location': 'vt_loc',
        'Transfer': 'vt_transfer',
        'Call': 'vt_call',
        'Access': 'vt_access',
        'Message': 'vt_msg',
        'Movement': 'vt_movement',
        'Impersonation': 'vt_impersonation',
    }

    # ── 그래프 라벨 → 개념명 (역방향)  (25종) ──
    CONCEPT_LOOKUP = {
        'vt_src': 'Source',
        'vt_case': 'Case',
        'vt_petition': 'Petition',
        'pt_cluster': 'PetitionCluster',
        'vt_psn': 'Person',
        'vt_org': 'Organization',
        'vt_bacnt': 'BankAccount',
        'vt_crypto': 'CryptoWallet',
        'vt_ip': 'NetworkTrace',
        'vt_site': 'WebTrace',
        'site_cluster': 'SiteCluster',
        'vt_file': 'FileTrace',
        'vt_id': 'DigitalID',
        'vt_email': 'Email',
        'vt_telno': 'Phone',
        'vt_vhcl': 'Vehicle',
        'vt_dev': 'Device',
        'vt_atm': 'ATM',
        'vt_loc': 'Location',
        'vt_transfer': 'Transfer',
        'vt_call': 'Call',
        'vt_access': 'Access',
        'vt_msg': 'Message',
        'vt_movement': 'Movement',
        'vt_impersonation': 'Impersonation',
    }

    # ── 라벨 → 한글명 (UI·보고서 표기용)  (25종) ──
    LABEL_KO_MAP = {
        'vt_src': '소스',
        'vt_case': '사건',
        'vt_petition': '진정서',
        'pt_cluster': '진정서군집',
        'vt_psn': '인물',
        'vt_org': '조직',
        'vt_bacnt': '계좌',
        'vt_crypto': '가상자산',
        'vt_ip': 'IP주소',
        'vt_site': '사이트',
        'site_cluster': '피싱캠페인군집',
        'vt_file': '파일',
        'vt_id': '디지털ID',
        'vt_email': '이메일',
        'vt_telno': '전화번호',
        'vt_vhcl': '차량',
        'vt_dev': '기기',
        'vt_atm': 'ATM',
        'vt_loc': '위치',
        'vt_transfer': '이체',
        'vt_call': '통화',
        'vt_access': '접속',
        'vt_msg': '메시지',
        'vt_movement': '이동이벤트',
        'vt_impersonation': '사칭이벤트',
    }

    # ── 전 엣지 공통 메타 속성과 타입  (11종) ──
    EDGE_META_SCHEMA = {
        'edge_id': str,
        'source_id': str,
        'rec_created': str,
        'creation_method': str,
        'confidence': float,
        'credibility': int,
        'verified': bool,
        'valid_from': str,
        'valid_to': str,
        'verified_by': str,
        'verified_at': str,
    }

    # ── 노드 식별자 규약 — canonical_field·정규화·해시 형식 (적재 멱등성의 근거)  (25종) ──
    NODE_ID_STANDARD = {
        'vt_bacnt': {'canonical_field': 'account_no',
                     'id_formats': ['plain_dash', 'md5', 'sha256'],
                     'default_format': 'plain_dash',
                     'normalization': 'strip_whitespace/dash + lowercase'},
        'vt_telno': {'canonical_field': 'telno', 'id_formats': ['no_hyphen_e164', 'md5'], 'default_format': 'no_hyphen_e164'},
        'vt_site': {'canonical_field': 'url_addr', 'id_formats': ['normalized_url'], 'default_format': 'normalized_url'},
        'vt_id': {'canonical_field': '(platform, id_val)', 'id_formats': ['plain'], 'default_format': 'plain'},
        'vt_ip': {'canonical_field': 'ip_addr', 'id_formats': ['ipv4_dotted', 'ipv6'], 'default_format': 'ipv4_dotted'},
        'vt_file': {'canonical_field': 'hash_val', 'id_formats': ['md5', 'sha1', 'sha256'], 'default_format': 'sha256'},
        'vt_psn': {'canonical_field': 'psn_id', 'id_formats': ['plain'], 'default_format': 'plain'},
        'pt_cluster': {'canonical_field': 'cluster_id',
                       'id_formats': ['plain'],
                       'default_format': 'plain',
                       'prefix_convention': {'investigation': 'ptc-{year}-{seq:04d}', 'osint': 'osint-ptc-{seq:04d}'}},
        'site_cluster': {'canonical_field': 'cluster_id',
                         'id_formats': ['plain'],
                         'default_format': 'plain',
                         'prefix_convention': {'investigation': 'sc-{year}-{seq:04d}', 'osint': 'osint-sc-{seq:04d}'}},
        'vt_src': {'canonical_field': 'src_id', 'id_formats': ['plain'], 'default_format': 'plain'},
        'vt_case': {'canonical_field': 'incdnt_no', 'id_formats': ['plain'], 'default_format': 'plain'},
        'vt_petition': {'canonical_field': 'petition_id', 'id_formats': ['plain'], 'default_format': 'plain'},
        'vt_org': {'canonical_field': 'org_id', 'id_formats': ['plain'], 'default_format': 'plain'},
        'vt_email': {'canonical_field': 'email_addr', 'id_formats': ['normalized'], 'default_format': 'normalized'},
        'vt_crypto': {'canonical_field': 'wallet_addr', 'id_formats': ['base58check'], 'default_format': 'base58check'},
        'vt_vhcl': {'canonical_field': 'vhclno', 'id_formats': ['plain'], 'default_format': 'plain'},
        'vt_dev': {'canonical_field': 'dev_id', 'id_formats': ['plain', 'imei'], 'default_format': 'plain'},
        'vt_atm': {'canonical_field': 'atm_id', 'id_formats': ['plain'], 'default_format': 'plain'},
        'vt_loc': {'canonical_field': 'loc_id', 'id_formats': ['plain', 'geohash'], 'default_format': 'plain'},
        'vt_transfer': {'canonical_field': 'transfer_id', 'id_formats': ['uuid'], 'default_format': 'uuid'},
        'vt_call': {'canonical_field': 'call_id', 'id_formats': ['uuid'], 'default_format': 'uuid'},
        'vt_access': {'canonical_field': 'access_id', 'id_formats': ['uuid'], 'default_format': 'uuid'},
        'vt_msg': {'canonical_field': 'msg_id', 'id_formats': ['uuid'], 'default_format': 'uuid'},
        'vt_movement': {'canonical_field': 'mov_id', 'id_formats': ['uuid'], 'default_format': 'uuid'},
        'vt_impersonation': {'canonical_field': 'impersonation_id', 'id_formats': ['uuid'], 'default_format': 'uuid'},
    }

    # ── RDB 표준테이블 크로스워크 (standard 키가 현행)  (25종) ──
    STANDARD_TABLE_MAP = {
        'vt_src': {'standard': 'TB_DATA_SOU_A', 'public_v2': 'TB_DATA_SRC', 'test_v40': None},
        'vt_case': {'standard': 'TB_INCDNT_M', 'public_v2': 'TB_INCDNT_MST', 'test_v40': 'tb_incdnt_mst'},
        'vt_petition': {'standard': 'TB_PETTN_M', 'public_v2': 'TB_PETTN_MST', 'test_v40': None},
        'vt_psn': {'standard': 'TB_PSN_M', 'public_v2': 'TB_PRSN', 'test_v40': 'tb_prsn', 'std_columns': {'occp_nm': 'CR_NM'}},
        'vt_org': {'standard': 'TB_INST_M', 'public_v2': 'TB_INST', 'test_v40': None},
        'vt_bacnt': {'standard': 'TB_FNNC_BACNT_M', 'public_v2': 'TB_FIN_BACNT', 'test_v40': 'tb_fin_bacnt'},
        'vt_telno': {'standard': 'TB_TELNO_M', 'public_v2': 'TB_TELNO_MST', 'test_v40': 'tb_telno_mst'},
        'vt_ip': {'standard': 'TB_IP_ADDR_M', 'public_v2': None, 'test_v40': None},
        'vt_site': {'standard': 'TB_WEB_DMN_M', 'public_v2': 'TB_WEB_DMN', 'test_v40': None},
        'vt_file': {'standard': 'TB_DGTL_FILE_LIST_M', 'public_v2': 'TB_DGTL_FILE_INVNT', 'test_v40': None},
        'vt_vhcl': {'standard': 'TB_VHCL_M', 'public_v2': 'TB_VHCL_MST', 'test_v40': None},
        'vt_id': {'standard': 'TB_DGTL_ID_M', 'public_v2': 'TB_DGTL_ID_MST', 'test_v40': None},
        'vt_email': {'standard': 'TB_EML_ADDR_M', 'public_v2': 'TB_EMAIL_MST', 'test_v40': None},
        'vt_crypto': {'standard': None, 'public_v2': 'TB_CRYPTO_WALLET_MST', 'test_v40': None},
        'vt_dev': {'standard': 'TB_ISTR_M', 'public_v2': 'TB_DEV_MST', 'test_v40': None},
        'vt_atm': {'standard': 'TB_ATM_M', 'public_v2': 'TB_ATM_MST', 'test_v40': None},
        'vt_loc': {'standard': 'TB_PSTN_M', 'public_v2': 'TB_LOC_MST', 'test_v40': None},
        'vt_transfer': {'standard': 'TB_FNNC_BACNT_DLNG_T', 'public_v2': 'TB_FIN_BACNT_DLNG', 'test_v40': 'tb_fin_bacnt_dlng'},
        'vt_call': {'standard': 'TB_TELNO_CALL_D',
                    'public_v2': 'TB_TELNO_CALL_DTL',
                    'test_v40': 'tb_telno_call_dtl',
                    'std_columns': {'call_strt_dt': 'CALL_STRT_DT', 'call_dur_sec': 'CALL_HR'}},
        'vt_msg': {'standard': ['TB_TELNO_SMS_MSG_T', 'TB_CTT_MSG_T'], 'public_v2': ['TB_TELNO_SMS_MSG', 'TB_CHAT_MSG'], 'test_v40': None},
        'vt_access': {'standard': 'TB_SYS_LGN_EVT_T',
                      'public_v2': 'TB_SYS_LGN_EVT',
                      'test_v40': None,
                      'std_columns': {'access_dt': 'CNTN_DT', 'access_type': 'CNTN_TYP_CD'}},
        'vt_movement': {'standard': ['TB_MOBL_PSTN_EVT_T', 'TB_TRFC_CARD_MVMN_T', 'TB_VHCL_NOPLT_RECG_EVT_T'],
                        'public_v2': ['TB_GEO_MBL_LOC_EVT', 'TB_VHCL_LPR_EVT'],
                        'test_v40': None},
        'vt_impersonation': {'standard': 'TB_FAAS_EVT_T', 'public_v2': 'TB_IMPRSN_REL', 'test_v40': None},
        'pt_cluster': {'standard': 'TB_PETTN_CLSTR_T', 'public_v2': 'TB_PETTN_CLSTR', 'test_v40': None},
        'site_cluster': {'standard': 'TB_OSINT_SITE_CLSTR_M', 'public_v2': None, 'test_v40': None},
    }

    # ── [부록] 원본 컬럼명 → 표준 속성 추론 규칙 (전처리 힌트)  (31종) ──
    COLUMN_PATTERNS = {
        'case': {'patterns': ['사건', 'case', '사건번호', '접수번호', 'flnm', 'incdnt_no'],
                 'kics_label': 'vt_case',
                 'kics_property': 'flnm',
                 'description': '사건번호/관리번호'},
        'petition': {'patterns': ['진정서', 'petition', '신고번호', 'dclr_sn', 'complaint', '민원'],
                     'kics_label': 'vt_petition',
                     'kics_property': 'petition_id',
                     'description': '진정서/신고접수번호'},
        'person': {'patterns': ['이름', 'name', '성명', '피해자', '피의자', '인물', 'korn_flnm'], 'kics_label': 'vt_psn', 'kics_property': 'name', 'description': '인물'},
        'suspect': {'patterns': ['피의자', 'suspect', '용의자', '범인', 'rrno', '주민번호'],
                    'kics_label': 'vt_psn',
                    'kics_property': 'rrno_hash',
                    'description': '피의자 식별자 (주민번호 → 해시)'},
        'account': {'patterns': ['계좌', 'account', 'bacnt', 'actno', 'bank', '은행', 'account_no'],
                    'kics_label': 'vt_bacnt',
                    'kics_property': 'account_no',
                    'description': '계좌번호'},
        'bank_cd': {'patterns': ['은행코드', 'bank_cd', 'bank_code', '금융기관코드'],
                    'kics_label': 'vt_bacnt',
                    'kics_property': 'bank_cd',
                    'is_attribute': True,
                    'description': '은행코드 (account_no와 복합 PK)'},
        'phone': {'patterns': ['전화', 'phone', 'telno', 'tel', 'mobile', '휴대폰', '연락처'],
                  'kics_label': 'vt_telno',
                  'kics_property': 'telno',
                  'description': '전화번호'},
        'ip': {'patterns': ['IP', 'ip주소', 'ip_addr', 'ipaddr', '아이피'], 'kics_label': 'vt_ip', 'kics_property': 'ip_addr', 'description': 'IP 주소'},
        'site': {'patterns': ['사이트', 'site', 'url', 'url_addr', 'domain', '웹', '링크'],
                 'kics_label': 'vt_site',
                 'kics_property': 'url_addr',
                 'description': '웹사이트/URL'},
        'file': {'patterns': ['파일', 'file', 'filename', 'file_nm', 'hash', 'hash_val'],
                 'kics_label': 'vt_file',
                 'kics_property': 'hash_val',
                 'description': '파일 (SHA-256 해시 기준)'},
        'user_id': {'patterns': ['사용자ID', 'user_id', 'login_id', 'account_id', 'uid', '아이디'],
                    'kics_label': 'vt_id',
                    'kics_property': 'id_val',
                    'description': '디지털 ID/계정'},
        'nickname': {'patterns': ['닉네임', 'nickname', 'nick', '별명', 'alias'], 'kics_label': 'vt_id', 'kics_property': 'id_val', 'description': '닉네임/별명'},
        'email': {'patterns': ['이메일', 'email', 'e-mail', 'mail', 'email_addr', '전자우편'],
                  'kics_label': 'vt_email',
                  'kics_property': 'email_addr',
                  'description': '이메일 주소'},
        'vehicle': {'patterns': ['차량', 'vehicle', '차량번호', 'vhclno', 'car', '번호판'], 'kics_label': 'vt_vhcl', 'kics_property': 'vhclno', 'description': '차량 번호'},
        'crypto': {'patterns': ['지갑', 'wallet', 'wallet_addr', '가상자산', 'crypto', 'btc', 'eth'],
                   'kics_label': 'vt_crypto',
                   'kics_property': 'wallet_addr',
                   'description': '가상자산 지갑 주소'},
        'atm': {'patterns': ['atm', 'atm_id', 'atm_mng_no', '현금인출기'], 'kics_label': 'vt_atm', 'kics_property': 'atm_id', 'description': 'ATM 관리번호'},
        'device': {'patterns': ['기기', 'device', 'imei', 'device_id', 'mac', 'mac_addr', '단말기', '중계기'],
                   'kics_label': 'vt_dev',
                   'kics_property': 'device_id',
                   'description': '기기 (IMEI·MAC 주소 기준 식별, relay_station 포함)'},
        'org': {'patterns': ['조직', 'org', '기관', '회사', '은행명', 'institution', 'inst_nm'],
                'kics_label': 'vt_org',
                'kics_property': 'org_name',
                'description': '조직/기관명'},
        'date': {'patterns': ['일시', 'date', '시간', 'time', '발생일시', '거래일시', 'occrn_dt', 'dlng_dt'],
                 'kics_label': '',
                 'kics_property': 'timestamp',
                 'is_attribute': True,
                 'description': '사건/이벤트 발생 일시'},
        'amount': {'patterns': ['금액', 'amount', '거래금액', '피해금액', 'dlng_amt', 'dam_amt'],
                   'kics_label': '',
                   'kics_property': 'amount',
                   'is_attribute': True,
                   'description': '이체/피해 금액'},
        'damage_amt': {'patterns': ['피해금액', 'damage_amount', '피해액', 'dam_amt'],
                       'kics_label': '',
                       'kics_property': 'damage_amount',
                       'is_attribute': True,
                       'description': '피해 금액'},
        'sender': {'patterns': ['출금', '송금계좌', '보낸사람', 'from', 'dsptch', 'sender'],
                   'kics_label': 'vt_transfer',
                   'kics_property': 'from_account',
                   'description': '이체 출발 계좌'},
        'receiver': {'patterns': ['입금', '수취계좌', '받는사람', 'to', 'rcptn', 'receiver'],
                     'kics_label': 'vt_transfer',
                     'kics_property': 'to_account',
                     'description': '이체 도착 계좌'},
        'caller': {'patterns': ['발신', 'caller', '발신번호', 'dsptch_telno'], 'kics_label': 'vt_telno', 'kics_property': 'telno', 'description': '발신 번호'},
        'callee': {'patterns': ['수신', 'callee', '수신번호', 'rcptn_telno'], 'kics_label': 'vt_telno', 'kics_property': 'telno', 'description': '수신 번호'},
        'duration': {'patterns': ['통화시간', 'duration', 'call_dur_sec'],
                     'kics_label': '',
                     'kics_property': 'call_dur_sec',
                     'is_attribute': True,
                     'description': '통화 시간 (초)'},
        'lat': {'patterns': ['위도', 'lat', 'latitude', 'bsst_lat'], 'kics_label': '', 'kics_property': 'lat', 'is_attribute': True, 'description': '위도 좌표'},
        'lng': {'patterns': ['경도', 'lng', 'longitude', 'bsst_lot'], 'kics_label': '', 'kics_property': 'lng', 'is_attribute': True, 'description': '경도 좌표'},
        'crime': {'patterns': ['죄명', '범죄유형', 'crime', '범죄유형명', 'incdnt_typ_cd'],
                  'kics_label': 'vt_case',
                  'kics_property': 'crime_type',
                  'is_attribute': True,
                  'description': '범죄 유형/죄명'},
        'message': {'patterns': ['메시지', 'message', '내용', 'content', '문자내용', '채팅'],
                    'kics_label': 'vt_msg',
                    'kics_property': 'content_hash',
                    'description': '메시지 내용 (해시)'},
        'sequence': {'patterns': ['순번', '번호', 'seq', 'index', 'idx', 'no'],
                     'kics_label': '',
                     'kics_property': 'seq',
                     'is_attribute': True,
                     'description': '순서 번호'},
    }

    # ── [부록] 속성 타입 → RDB 타입  (28종) ──
    COLUMN_TYPE_TO_RDB = {
        'case_id': 'case',
        'case': 'case',
        'petition': 'petition',
        'suspect': 'suspect',
        'phone': 'phone',
        'account': 'account',
        'bank_cd': 'bank_cd',
        'ip': 'ip',
        'user_id': 'user_id',
        'person': 'name',
        'nickname': 'nickname',
        'email': 'email',
        'crypto': 'crypto',
        'date': 'date',
        'amount': 'amount',
        'crime': 'crime',
        'sender': 'sender',
        'receiver': 'receiver',
        'caller': 'caller',
        'callee': 'callee',
        'duration': 'duration',
        'site': 'site',
        'file': 'file',
        'message': 'message',
        'org': 'org',
        'vehicle': 'vehicle',
        'lat': 'lat',
        'lng': 'lng',
    }

    # ── 헬퍼 (스펙에서 바로 파생되는 것만) ──

    @classmethod
    def active_relationships(cls):
        """deprecated 를 제외한 엣지 정의."""
        return {k: v for k, v in cls.RELATIONSHIPS.items()
                if not (isinstance(v, dict) and v.get('deprecated'))}

    @classmethod
    def label_of(cls, concept_or_label):
        """개념명 → 그래프 라벨. 이미 라벨이면 그대로 돌려준다."""
        return cls.GDB_LABEL_MAP.get(concept_or_label, concept_or_label)

    @classmethod
    def concept_of(cls, label):
        """그래프 라벨 → 개념명."""
        return cls.CONCEPT_LOOKUP.get(label, label)

    @classmethod
    def key_field(cls, label):
        """라벨의 식별 속성명. NODE_ID_STANDARD 가 우선, 없으면 ENTITIES.properties[0]."""
        std = cls.NODE_ID_STANDARD.get(label)
        if isinstance(std, dict) and std.get('canonical_field'):
            return std['canonical_field']
        ent = cls.ENTITIES.get(cls.concept_of(label))
        props = ent.get('properties') if isinstance(ent, dict) else None
        return props[0] if props else None
