-- ============================================================
-- CyberCOP V4.0 Database Standardization Patch DDL
--
-- 본 DDL은 CyberCOP 데이터베이스 표준화 작업 결과를 반영하기
-- 위해 작성되었으며, 아래 문서를 기준으로 적용한다.
--
-- [참고 문서]
--  - CCOP RDB 데이터베이스 표준화 설계서 v3.6
--  - DA팀 DDL to CCOP V4.0 Compatibility Patch SQL v3.7
--
-- 주요 적용 사항
--  - 테이블명 표준화(TB_ Prefix 적용)
--  - 엔터티 및 속성 표준화
--  - 표준 용어/도메인 반영
--  - 컬럼명 및 주석 정비
--  - V4.0 호환성 패치 적용
--
-- ============================================================

-- ============================================================
-- 3.1 소스/메타 도메인
-- 설계 의도 : 데이터 출처(Provenance), 수집이력, 품질감사 관리
-- ============================================================

-- 자료원천관리 테이블
CREATE TABLE TB_DATA_SOU_A 
(
    SRC_ID    varchar(200) NOT NULL,
    SRC_NM    varchar(100) NOT NULL,
    SRC_TYP_CD    varchar(20) NOT NULL,
    CFRT_GRD_CD    numeric(3) DEFAULT 3 NOT NULL,
    CNTT_URL_ADDR    varchar(500),
    CLCT_DT    timestamp with time zone,
    UPDT_CYC_NM    varchar(20),
    ACTVTN_YN    character(1) DEFAULT 'Y' NOT NULL,
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT    timestamp with time zone,
    USER_ID    varchar(20)
);

COMMENT ON COLUMN TB_DATA_SOU_A.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_DATA_SOU_A.SRC_NM IS '출처명';
COMMENT ON COLUMN TB_DATA_SOU_A.SRC_TYP_CD IS '출처타입코드';
COMMENT ON COLUMN TB_DATA_SOU_A.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_DATA_SOU_A.CNTT_URL_ADDR IS '연락URL주소';
COMMENT ON COLUMN TB_DATA_SOU_A.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_DATA_SOU_A.UPDT_CYC_NM IS '갱신주기명';
COMMENT ON COLUMN TB_DATA_SOU_A.ACTVTN_YN IS '활성여부';
COMMENT ON COLUMN TB_DATA_SOU_A.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_DATA_SOU_A.MDFCN_DT IS '수정일시';
COMMENT ON COLUMN TB_DATA_SOU_A.USER_ID IS '사용자아이디';

COMMENT ON TABLE TB_DATA_SOU_A IS '자료원천관리';

CREATE UNIQUE INDEX TB_DATA_SOU_A_PK ON TB_DATA_SOU_A
( SRC_ID );

ALTER TABLE TB_DATA_SOU_A
 ADD CONSTRAINT TB_DATA_SOU_A_PK PRIMARY KEY 
 USING INDEX TB_DATA_SOU_A_PK;


-- 자료수집로그 테이블
CREATE TABLE TB_DATA_CLCT_L
(
    LOG_SN    BIGSERIAL NOT NULL,
    SRC_ID    varchar(200) NOT NULL,
    LOAD_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CLCT_TYP_CD    varchar(20),
    ACTV_TYP_CD    varchar(20),
    TBL_NM    varchar(300),
    TOT_NOCS    numeric(10) DEFAULT 0,
    SCS_NOCS    numeric(10) DEFAULT 0,
    FAIL_NOCS    numeric(10) DEFAULT 0,
    JOB_PRCS_RSLT_CD    varchar(5),
    ERR_MSG_CN    varchar(4000)
);

COMMENT ON COLUMN TB_DATA_CLCT_L.LOG_SN IS '로그일련번호';
COMMENT ON COLUMN TB_DATA_CLCT_L.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_DATA_CLCT_L.LOAD_DT IS '적재일시';
COMMENT ON COLUMN TB_DATA_CLCT_L.CLCT_TYP_CD IS '수집타입코드';
COMMENT ON COLUMN TB_DATA_CLCT_L.ACTV_TYP_CD IS '활동타입코드';
COMMENT ON COLUMN TB_DATA_CLCT_L.TBL_NM IS '테이블명';
COMMENT ON COLUMN TB_DATA_CLCT_L.TOT_NOCS IS '집계건수';
COMMENT ON COLUMN TB_DATA_CLCT_L.SCS_NOCS IS '성공건수';
COMMENT ON COLUMN TB_DATA_CLCT_L.FAIL_NOCS IS '실패건수';
COMMENT ON COLUMN TB_DATA_CLCT_L.JOB_PRCS_RSLT_CD IS '작업처리결과코드';
COMMENT ON COLUMN TB_DATA_CLCT_L.ERR_MSG_CN IS '오류메시지내용';

COMMENT ON TABLE TB_DATA_CLCT_L IS '자료수집로그';

CREATE UNIQUE INDEX TB_DATA_CLCT_L_PK ON TB_DATA_CLCT_L
( LOG_SN );

ALTER TABLE TB_DATA_CLCT_L
 ADD CONSTRAINT TB_DATA_CLCT_L_PK PRIMARY KEY 
 USING INDEX TB_DATA_CLCT_L_PK;

-- 자료품질검사로그 테이블
CREATE TABLE TB_DATA_QC_L
(
    QC_SN    BIGSERIAL NOT NULL,
    SRC_ID    varchar(200) NOT NULL,
    TBL_NM    varchar(300) NOT NULL,
    RCRD_KEY_VL    varchar(1000) NOT NULL,
    QC_RUL_CD    varchar(50) NOT NULL,
    QC_RSLT_CD    varchar(10) NOT NULL,
    QC_MSG_CN    varchar(4000),
    ADT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_DATA_QC_L.QC_SN IS '품질검사일련번호';
COMMENT ON COLUMN TB_DATA_QC_L.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_DATA_QC_L.TBL_NM IS '테이블명';
COMMENT ON COLUMN TB_DATA_QC_L.RCRD_KEY_VL IS '레코드KEY값';
COMMENT ON COLUMN TB_DATA_QC_L.QC_RUL_CD IS '품질검사규칙코드';
COMMENT ON COLUMN TB_DATA_QC_L.QC_RSLT_CD IS '품질검사결과코드';
COMMENT ON COLUMN TB_DATA_QC_L.QC_MSG_CN IS '품질검사메시지내용';
COMMENT ON COLUMN TB_DATA_QC_L.ADT_DT IS '감사일시';

COMMENT ON TABLE TB_DATA_QC_L IS '자료품질검사로그';

CREATE UNIQUE INDEX TB_DATA_QC_L_PK ON TB_DATA_QC_L
( QC_SN );

ALTER TABLE TB_DATA_QC_L
 ADD CONSTRAINT TB_DATA_QC_L_PK PRIMARY KEY 
 USING INDEX TB_DATA_QC_L_PK;

-- ============================================================
-- 3.2 사건/관리 도메인
-- 사건과 사건-인물 관계 관리
-- ============================================================

-- 사건기본 테이블
CREATE TABLE TB_INCDNT_M
(
    INCDNT_NO    varchar(20) NOT NULL,
    FLNM    varchar(50),
    INCDNT_NM    varchar(300) NOT NULL,
    INCDNT_TYP_CD    varchar(5),
    INCDNT_OCRN_YMD    character(8),
    END_DT    timestamp with time zone,
    TKCG_DEPT_NM    varchar(200),
    IVSTR_NM    varchar(100),
    POLSTN_NM    varchar(200),
    INCDNT_OTLN_CN    text,
    DAM_AMT    numeric(15),
    PRGRS_STTS_CD    varchar(20) DEFAULT 'OPEN',
    CRIM_TCNQ_CD    varchar(30),
    CRIM_STP_CD    varchar(20),
    RISK_GRD_CD    numeric(3),
    RISK_SCR    numeric(5,2),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT    timestamp with time zone,
    USER_ID    varchar(20),
    SRC_ID    varchar(200),
    SRC_DMN_ADDR    varchar(200),
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_INCDNT_M.INCDNT_NO IS '사건번호';
COMMENT ON COLUMN TB_INCDNT_M.FLNM IS '성명';
COMMENT ON COLUMN TB_INCDNT_M.INCDNT_NM IS '사건명';
COMMENT ON COLUMN TB_INCDNT_M.INCDNT_TYP_CD IS '사건타입코드';
COMMENT ON COLUMN TB_INCDNT_M.INCDNT_OCRN_YMD IS '사건발생일자';
COMMENT ON COLUMN TB_INCDNT_M.END_DT IS '종료일시';
COMMENT ON COLUMN TB_INCDNT_M.TKCG_DEPT_NM IS '담당부서명';
COMMENT ON COLUMN TB_INCDNT_M.IVSTR_NM IS '수사관명';
COMMENT ON COLUMN TB_INCDNT_M.POLSTN_NM IS '경찰서명';
COMMENT ON COLUMN TB_INCDNT_M.INCDNT_OTLN_CN IS '사건개요내용';
COMMENT ON COLUMN TB_INCDNT_M.DAM_AMT IS '피해금액';
COMMENT ON COLUMN TB_INCDNT_M.PRGRS_STTS_CD IS '진행상태코드';
COMMENT ON COLUMN TB_INCDNT_M.CRIM_TCNQ_CD IS '범죄수법코드';
COMMENT ON COLUMN TB_INCDNT_M.CRIM_STP_CD IS '범죄단계코드';
COMMENT ON COLUMN TB_INCDNT_M.RISK_GRD_CD IS '위험등급코드';
COMMENT ON COLUMN TB_INCDNT_M.RISK_SCR IS '위험점수';
COMMENT ON COLUMN TB_INCDNT_M.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_INCDNT_M.MDFCN_DT IS '수정일시';
COMMENT ON COLUMN TB_INCDNT_M.USER_ID IS '사용자아이디';
COMMENT ON COLUMN TB_INCDNT_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_INCDNT_M.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_INCDNT_M.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_INCDNT_M.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_INCDNT_M.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_INCDNT_M.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_INCDNT_M IS '사건기본';

CREATE UNIQUE INDEX TB_INCDNT_M_PK ON TB_INCDNT_M
( INCDNT_NO );

ALTER TABLE TB_INCDNT_M
 ADD CONSTRAINT TB_INCDNT_M_PK PRIMARY KEY 
 USING INDEX TB_INCDNT_M_PK;

-- 사건인물관계내역 테이블
CREATE TABLE TB_INCDNT_PSN_REL_T
(
    REL_SN    BIGSERIAL NOT NULL,
    INCDNT_NO    varchar(20) NOT NULL,
    PSN_ID    varchar(50) NOT NULL,
    ROLE_CD    varchar(20) NOT NULL,
    VLD_BGNG_DT    timestamp with time zone,
    VLD_END_DT    timestamp with time zone,
    CFRT    numeric(5,3) DEFAULT 1.000,
    VRFC_YN    character(1) DEFAULT 'N',
    VRFR_NM    varchar(150),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_INCDNT_PSN_REL_T.REL_SN IS '관계일련번호';
COMMENT ON COLUMN TB_INCDNT_PSN_REL_T.INCDNT_NO IS '사건번호';
COMMENT ON COLUMN TB_INCDNT_PSN_REL_T.PSN_ID IS '사람아이디';
COMMENT ON COLUMN TB_INCDNT_PSN_REL_T.ROLE_CD IS '역할코드';
COMMENT ON COLUMN TB_INCDNT_PSN_REL_T.VLD_BGNG_DT IS '유효시작일시';
COMMENT ON COLUMN TB_INCDNT_PSN_REL_T.VLD_END_DT IS '유효종료일시';
COMMENT ON COLUMN TB_INCDNT_PSN_REL_T.CFRT IS '신뢰도';
COMMENT ON COLUMN TB_INCDNT_PSN_REL_T.VRFC_YN IS '검증여부';
COMMENT ON COLUMN TB_INCDNT_PSN_REL_T.VRFR_NM IS '검증자명';
COMMENT ON COLUMN TB_INCDNT_PSN_REL_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_INCDNT_PSN_REL_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_INCDNT_PSN_REL_T IS '사건인물관계내역';

CREATE UNIQUE INDEX TB_INCDNT_PSN_REL_T_PK ON TB_INCDNT_PSN_REL_T
( REL_SN );

ALTER TABLE TB_INCDNT_PSN_REL_T
 ADD CONSTRAINT TB_INCDNT_PSN_REL_T_PK PRIMARY KEY 
 USING INDEX TB_INCDNT_PSN_REL_T_PK;

-- ============================================================
-- 3.3 진정서 도메인
-- 진정서, 군집화, 처리이력 관리
-- ============================================================

-- 진정서기본테이블
CREATE TABLE TB_PETTN_M
(
    DCLR_SN    BIGSERIAL NOT NULL,
    PETTN_ID    varchar(50) NOT NULL,
    RCPT_DT    timestamp with time zone NOT NULL,
    RCPT_CHNL_CD    varchar(20) NOT NULL,
    POLSTN_NM    varchar(200),
    CRIM_SE_CD    varchar(5),
    CRIM_NM    varchar(300),
    DAM_AMT    numeric(15),
    INCDNT_OCRN_YMD    character(8),
    VCTM_NM    varchar(150),
    VCTM_TELNO    varchar(11),
    SMRY_CN    varchar(4000),
    PRGRS_STTS_CD    varchar(20) DEFAULT 'PENDING' NOT NULL,
    REL_INCDNT_NO    varchar(20),
    PREPROC_SOU_ID    varchar(50),
    OCR_CFRT    numeric(5,3),
    NER_CFRT    numeric(5,3),
    SCHM_VER_NM    varchar(20),
    FILE_PATH_NM    varchar(300),
    CRIM_TCNQ_CD    varchar(30),
    CRIM_STP_CN    varchar(200),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT    timestamp with time zone,
    USER_ID    varchar(20),
    SRC_DMN_ADDR    varchar(200),
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_PETTN_M.DCLR_SN IS '신고일련번호';
COMMENT ON COLUMN TB_PETTN_M.PETTN_ID IS '진정서아이디';
COMMENT ON COLUMN TB_PETTN_M.RCPT_DT IS '접수일시';
COMMENT ON COLUMN TB_PETTN_M.RCPT_CHNL_CD IS '접수채널코드';
COMMENT ON COLUMN TB_PETTN_M.POLSTN_NM IS '경찰서명';
COMMENT ON COLUMN TB_PETTN_M.CRIM_SE_CD IS '범죄구분코드';
COMMENT ON COLUMN TB_PETTN_M.CRIM_NM IS '범죄명';
COMMENT ON COLUMN TB_PETTN_M.DAM_AMT IS '피해금액';
COMMENT ON COLUMN TB_PETTN_M.INCDNT_OCRN_YMD IS '사건발생일자';
COMMENT ON COLUMN TB_PETTN_M.VCTM_NM IS '피해자명';
COMMENT ON COLUMN TB_PETTN_M.VCTM_TELNO IS '피해자전화번호';
COMMENT ON COLUMN TB_PETTN_M.SMRY_CN IS '요약내용';
COMMENT ON COLUMN TB_PETTN_M.PRGRS_STTS_CD IS '진행상태코드';
COMMENT ON COLUMN TB_PETTN_M.REL_INCDNT_NO IS '관계사건번호';
COMMENT ON COLUMN TB_PETTN_M.PREPROC_SOU_ID IS '전처리원천아이디';
COMMENT ON COLUMN TB_PETTN_M.OCR_CFRT IS 'OCR신뢰도';
COMMENT ON COLUMN TB_PETTN_M.NER_CFRT IS 'NER신뢰도';
COMMENT ON COLUMN TB_PETTN_M.SCHM_VER_NM IS '스키마버전명';
COMMENT ON COLUMN TB_PETTN_M.FILE_PATH_NM IS '파일경로명';
COMMENT ON COLUMN TB_PETTN_M.CRIM_TCNQ_CD IS '범죄수법코드';
COMMENT ON COLUMN TB_PETTN_M.CRIM_STP_CN IS '범죄단계내용';
COMMENT ON COLUMN TB_PETTN_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_PETTN_M.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_PETTN_M.MDFCN_DT IS '수정일시';
COMMENT ON COLUMN TB_PETTN_M.USER_ID IS '사용자아이디';
COMMENT ON COLUMN TB_PETTN_M.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_PETTN_M.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_PETTN_M.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_PETTN_M.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_PETTN_M.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_PETTN_M IS '진정서기본';

CREATE UNIQUE INDEX TB_PETTN_M_PK ON TB_PETTN_M
( DCLR_SN );

ALTER TABLE TB_PETTN_M
 ADD CONSTRAINT TB_PETTN_M_PK PRIMARY KEY 
 USING INDEX TB_PETTN_M_PK;

-- 진정서군집내역 테이블
CREATE TABLE TB_PETTN_CLSTR_T
(
    CLST_SN    BIGSERIAL NOT NULL,
    CRTR_PETTN_SN    numeric(10) NOT NULL,
    COMP_PETTN_SN    numeric(10) NOT NULL,
    CLST_ID    varchar(50),
    SIMIL_SCR    numeric(5,3),
    SIMIL_BSS_CD    varchar(50),
    AUTO_CRT_YN    character(1) DEFAULT 'Y' NOT NULL,
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_PETTN_CLSTR_T.CLST_SN IS '클러스터일련번호';
COMMENT ON COLUMN TB_PETTN_CLSTR_T.CRTR_PETTN_SN IS '기준진정서일련번호';
COMMENT ON COLUMN TB_PETTN_CLSTR_T.COMP_PETTN_SN IS '비교진정서일련번호';
COMMENT ON COLUMN TB_PETTN_CLSTR_T.CLST_ID IS '클러스터아이디';
COMMENT ON COLUMN TB_PETTN_CLSTR_T.SIMIL_SCR IS '유사도점수';
COMMENT ON COLUMN TB_PETTN_CLSTR_T.SIMIL_BSS_CD IS '유사도근거코드';
COMMENT ON COLUMN TB_PETTN_CLSTR_T.AUTO_CRT_YN IS '자동생성여부';
COMMENT ON COLUMN TB_PETTN_CLSTR_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_PETTN_CLSTR_T IS '진정서군집내역';

CREATE UNIQUE INDEX TB_PETTN_CLSTR_T_PK ON TB_PETTN_CLSTR_T
( CLST_SN );

ALTER TABLE TB_PETTN_CLSTR_T
 ADD CONSTRAINT TB_PETTN_CLSTR_T_PK PRIMARY KEY 
 USING INDEX TB_PETTN_CLSTR_T_PK;

-- 진정서처리로그
CREATE TABLE TB_PETTN_PRCS_L
(
    LOG_SN    BIGSERIAL NOT NULL,
    PETTN_SN    numeric(10) NOT NULL,
    PRCS_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    BFR_PRGRS_STTS_CD    varchar(20),
    NEW_PRGRS_STTS_CD    varchar(20) NOT NULL,
    PRCR_ID    varchar(20),
    PRCS_RSN    varchar(4000)
);

COMMENT ON COLUMN TB_PETTN_PRCS_L.LOG_SN IS '로그일련번호';
COMMENT ON COLUMN TB_PETTN_PRCS_L.PETTN_SN IS '진정서일련번호';
COMMENT ON COLUMN TB_PETTN_PRCS_L.PRCS_DT IS '처리일시';
COMMENT ON COLUMN TB_PETTN_PRCS_L.BFR_PRGRS_STTS_CD IS '이전진행상태코드';
COMMENT ON COLUMN TB_PETTN_PRCS_L.NEW_PRGRS_STTS_CD IS '신규진행상태코드';
COMMENT ON COLUMN TB_PETTN_PRCS_L.PRCR_ID IS '처리자아이디';
COMMENT ON COLUMN TB_PETTN_PRCS_L.PRCS_RSN IS '처리사유';

COMMENT ON TABLE TB_PETTN_PRCS_L IS '진정서처리로그';

CREATE UNIQUE INDEX TB_PETTN_PRCS_L_PK ON TB_PETTN_PRCS_L
( LOG_SN );

ALTER TABLE TB_PETTN_PRCS_L
 ADD CONSTRAINT TB_PETTN_PRCS_L_PK PRIMARY KEY 
 USING INDEX TB_PETTN_PRCS_L_PK;

-- ============================================================
-- 3.4 사람/주체 도메인
-- 사람 및 기관 정보 관리
-- ============================================================

-- 사람기본 테이블
CREATE TABLE TB_PSN_M
(
    PSN_ID    varchar(50) NOT NULL,
    KORN_FLNM    varchar(150),
    RRNO_HASH_VL    varchar(64),
    RRNO_ENCPT_VL    bytea,
    GNDR_CD    varchar(1),
    NTNLTY_CD    varchar(5),
    BRDT    character(8),
    PNO    varchar(9),
    TCNQ_SOU_VL    varchar(50),
    RISK_GRD_CD    numeric(3) DEFAULT 1,
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT    timestamp with time zone,
    USER_ID    varchar(20),
    ANMT_PSN_YN    character(1) DEFAULT 'N'
);

COMMENT ON COLUMN TB_PSN_M.PSN_ID IS '사람아이디';
COMMENT ON COLUMN TB_PSN_M.KORN_FLNM IS '한글성명';
COMMENT ON COLUMN TB_PSN_M.RRNO_HASH_VL IS '주민등록번호해시값';
COMMENT ON COLUMN TB_PSN_M.RRNO_ENCPT_VL IS '주민등록번호암호화값';
COMMENT ON COLUMN TB_PSN_M.GNDR_CD IS '성별코드';
COMMENT ON COLUMN TB_PSN_M.NTNLTY_CD IS '국적코드';
COMMENT ON COLUMN TB_PSN_M.BRDT IS '생년월일';
COMMENT ON COLUMN TB_PSN_M.PNO IS '여권번호';
COMMENT ON COLUMN TB_PSN_M.TCNQ_SOU_VL IS '수법원천값';
COMMENT ON COLUMN TB_PSN_M.RISK_GRD_CD IS '위험등급코드';
COMMENT ON COLUMN TB_PSN_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_PSN_M.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_PSN_M.MDFCN_DT IS '수정일시';
COMMENT ON COLUMN TB_PSN_M.USER_ID IS '사용자아이디';
COMMENT ON COLUMN TB_PSN_M.ANMT_PSN_YN IS '익명사람여부';

COMMENT ON TABLE TB_PSN_M IS '사람기본';

CREATE UNIQUE INDEX TB_PSN_M_PK ON TB_PSN_M
( PSN_ID );

ALTER TABLE TB_PSN_M
 ADD CONSTRAINT TB_PSN_M_PK PRIMARY KEY 
 USING INDEX TB_PSN_M_PK;

-- 기관기본 테이블
CREATE TABLE TB_INST_M
(
    INST_ID    varchar(200) NOT NULL,
    INST_NM    varchar(200) NOT NULL,
    INST_SE_CD    varchar(2),
    BRNO    character(10),
    BANK_CD    varchar(30),
    ADDR    varchar(200),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_INST_M.INST_ID IS '기관아이디';
COMMENT ON COLUMN TB_INST_M.INST_NM IS '기관명';
COMMENT ON COLUMN TB_INST_M.INST_SE_CD IS '기관구분코드';
COMMENT ON COLUMN TB_INST_M.BRNO IS '사업자등록번호';
COMMENT ON COLUMN TB_INST_M.BANK_CD IS '은행코드';
COMMENT ON COLUMN TB_INST_M.ADDR IS '주소';
COMMENT ON COLUMN TB_INST_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_INST_M.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_INST_M IS '기관기본';

CREATE UNIQUE INDEX TB_INST_M_PK ON TB_INST_M
( INST_ID );

ALTER TABLE TB_INST_M
 ADD CONSTRAINT TB_INST_M_PK PRIMARY KEY 
 USING INDEX TB_INST_M_PK;

-- ============================================================
-- 3.5 금융 도메인
-- 계좌 및 거래 정보 관리
-- ============================================================

-- 금융계좌기본 테이블
CREATE TABLE TB_FNNC_BACNT_M
(
    ACTNO    varchar(20) NOT NULL,
    BANK_CD    varchar(30) NOT NULL,
    BANK_NM    varchar(100),
    DPSTR_NM    varchar(100),
    BACNT_TYP_CD    character(3),
    BACNT_ESTBL_YMD    character(8),
    INST_ID    varchar(200),
    ACNT_LCK_YN    character(1) DEFAULT 'N',
    NER_BR_YN    character(1) DEFAULT 'N',
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT    timestamp with time zone,
    USER_ID    varchar(20)
);

COMMENT ON COLUMN TB_FNNC_BACNT_M.ACTNO IS '계좌번호';
COMMENT ON COLUMN TB_FNNC_BACNT_M.BANK_CD IS '은행코드';
COMMENT ON COLUMN TB_FNNC_BACNT_M.BANK_NM IS '은행명';
COMMENT ON COLUMN TB_FNNC_BACNT_M.DPSTR_NM IS '예금주명';
COMMENT ON COLUMN TB_FNNC_BACNT_M.BACNT_TYP_CD IS '계좌타입코드';
COMMENT ON COLUMN TB_FNNC_BACNT_M.BACNT_ESTBL_YMD IS '계좌개설일자';
COMMENT ON COLUMN TB_FNNC_BACNT_M.INST_ID IS '기관아이디';
COMMENT ON COLUMN TB_FNNC_BACNT_M.ACNT_LCK_YN IS '계정잠금여부';
COMMENT ON COLUMN TB_FNNC_BACNT_M.NER_BR_YN IS 'NER병과여부';
COMMENT ON COLUMN TB_FNNC_BACNT_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_FNNC_BACNT_M.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_FNNC_BACNT_M.MDFCN_DT IS '수정일시';
COMMENT ON COLUMN TB_FNNC_BACNT_M.USER_ID IS '사용자아이디';

COMMENT ON TABLE TB_FNNC_BACNT_M IS '금융계좌기본';

CREATE UNIQUE INDEX TB_FNNC_BACNT_M_PK ON TB_FNNC_BACNT_M
( ACTNO,BANK_CD );

ALTER TABLE TB_FNNC_BACNT_M
 ADD CONSTRAINT TB_FNNC_BACNT_M_PK PRIMARY KEY 
 USING INDEX TB_FNNC_BACNT_M_PK;

-- 금융계좌거래내역 테이블
CREATE TABLE TB_FNNC_BACNT_DLNG_T
(
    DLNG_SN    BIGSERIAL NOT NULL,
    ACTNO    varchar(20) NOT NULL,
    BANK_CD    varchar(30) NOT NULL,
    DLNG_DT    timestamp with time zone NOT NULL,
    DLNG_SE_CD    varchar(10) NOT NULL,
    DLNG_AMT    numeric(15) NOT NULL,
    NOW_BLNC    numeric(15),
    ADDRSE_ACTNO    varchar(20),
    RLT_BANK_CD    varchar(10),
    RLT_DPSTR_NM    varchar(100),
    DLNG_MEMO_CN    varchar(500),
    ATM_MNG_NO    varchar(20),
    HOP_CNT    numeric(3) DEFAULT 1,
    DUBT_DLNG_YN    character(1) DEFAULT 'N',
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.DLNG_SN IS '거래일련번호';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.ACTNO IS '계좌번호';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.BANK_CD IS '은행코드';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.DLNG_DT IS '거래일시';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.DLNG_SE_CD IS '거래구분코드';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.DLNG_AMT IS '거래금액';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.NOW_BLNC IS '현재잔액';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.ADDRSE_ACTNO IS '수취인계좌번호';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.RLT_BANK_CD IS '상대은행코드';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.RLT_DPSTR_NM IS '상대예금주명';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.DLNG_MEMO_CN IS '거래메모내용';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.ATM_MNG_NO IS 'ATM관리번호';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.HOP_CNT IS '홉수';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.DUBT_DLNG_YN IS '의심거래여부';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_FNNC_BACNT_DLNG_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_FNNC_BACNT_DLNG_T IS '금융계좌거래내역';

CREATE UNIQUE INDEX TB_FNNC_BACNT_DLNG_T_PK ON TB_FNNC_BACNT_DLNG_T
( DLNG_SN );

ALTER TABLE TB_FNNC_BACNT_DLNG_T
 ADD CONSTRAINT TB_FNNC_BACNT_DLNG_T_PK PRIMARY KEY 
 USING INDEX TB_FNNC_BACNT_DLNG_T_PK;

-- ============================================================
-- 3.6 통신 도메인
-- 전화, 문자, 채팅 등 통신 정보
-- ============================================================

-- 전화번호기본테이블
CREATE TABLE TB_TELNO_M
(
    DSPTCH_TELNO    varchar(11) NOT NULL,
    NTN_CD    character(3) DEFAULT '+82',
    TLCMCO_NM    varchar(100),
    JOIN_TYP_CD    varchar(30),
    REG_YN    character(1) DEFAULT 'Y',
    NER_BR_YN    character(1) DEFAULT 'N',
    SBSR_NM    varchar(100),
    USER_IDNTF_NO    varchar(50),
    SPAM_CNT    numeric(4) DEFAULT 0,
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT    timestamp with time zone
);

COMMENT ON COLUMN TB_TELNO_M.DSPTCH_TELNO IS '발신전화번호';
COMMENT ON COLUMN TB_TELNO_M.NTN_CD IS '국가코드';
COMMENT ON COLUMN TB_TELNO_M.TLCMCO_NM IS '통신사명';
COMMENT ON COLUMN TB_TELNO_M.JOIN_TYP_CD IS '가입타입코드';
COMMENT ON COLUMN TB_TELNO_M.REG_YN IS '등록여부';
COMMENT ON COLUMN TB_TELNO_M.NER_BR_YN IS 'NER병과여부';
COMMENT ON COLUMN TB_TELNO_M.SBSR_NM IS '가입자명';
COMMENT ON COLUMN TB_TELNO_M.USER_IDNTF_NO IS '사용자식별번호';
COMMENT ON COLUMN TB_TELNO_M.SPAM_CNT IS '스팸수';
COMMENT ON COLUMN TB_TELNO_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_TELNO_M.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_TELNO_M.MDFCN_DT IS '수정일시';

COMMENT ON TABLE TB_TELNO_M IS '전화번호기본';

CREATE UNIQUE INDEX TB_TELNO_M_PK ON TB_TELNO_M
( DSPTCH_TELNO );

ALTER TABLE TB_TELNO_M
 ADD CONSTRAINT TB_TELNO_M_PK PRIMARY KEY 
 USING INDEX TB_TELNO_M_PK;

-- 통화상세내역테이블
CREATE TABLE TB_TELNO_CALL_D
(
    CALL_SN    BIGSERIAL NOT NULL,
    DSPTCH_TELNO    varchar(11) NOT NULL,
    RCPTN_TELNO    varchar(11) NOT NULL,
    CALL_STRT_DT    timestamp with time zone NOT NULL,
    CALL_HR    character(6) DEFAULT '0',
    CALL_TYP_CD    varchar(30),
    BSST_NM    varchar(256),
    BSST_LAT    numeric(16,10),
    BSST_LOT    numeric(13,10),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_TELNO_CALL_D.CALL_SN IS '통화일련번호';
COMMENT ON COLUMN TB_TELNO_CALL_D.DSPTCH_TELNO IS '발신전화번호';
COMMENT ON COLUMN TB_TELNO_CALL_D.RCPTN_TELNO IS '수신전화번호';
COMMENT ON COLUMN TB_TELNO_CALL_D.CALL_STRT_DT IS '통화개시일시';
COMMENT ON COLUMN TB_TELNO_CALL_D.CALL_HR IS '통화시간';
COMMENT ON COLUMN TB_TELNO_CALL_D.CALL_TYP_CD IS '통화타입코드';
COMMENT ON COLUMN TB_TELNO_CALL_D.BSST_NM IS '기지국명';
COMMENT ON COLUMN TB_TELNO_CALL_D.BSST_LAT IS '기지국위도';
COMMENT ON COLUMN TB_TELNO_CALL_D.BSST_LOT IS '기지국경도';
COMMENT ON COLUMN TB_TELNO_CALL_D.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_TELNO_CALL_D.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_TELNO_CALL_D IS '전화번호통화상세';

CREATE UNIQUE INDEX TB_TELNO_CALL_D_PK ON TB_TELNO_CALL_D
( CALL_SN );

ALTER TABLE TB_TELNO_CALL_D
 ADD CONSTRAINT TB_TELNO_CALL_D_PK PRIMARY KEY 
 USING INDEX TB_TELNO_CALL_D_PK;

-- 전화번호SMS메시지내역 테이블
CREATE TABLE TB_TELNO_SMS_MSG_T
(
    MSG_SN    BIGSERIAL NOT NULL,
    DSPTCH_TELNO    varchar(11) NOT NULL,
    RCPTN_TELNO    varchar(11) NOT NULL,
    DSPTCH_DT    timestamp with time zone NOT NULL,
    MSG_CN_HASH_VL    varchar(64),
    SPAM_YN    character(1) DEFAULT 'N',
    SENTMT_CD    varchar(20),
    ACNT_INCL_YN    character(1) DEFAULT 'N',
    URL_INCL_YN    character(1) DEFAULT 'N',
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_TELNO_SMS_MSG_T.MSG_SN IS '메시지일련번호';
COMMENT ON COLUMN TB_TELNO_SMS_MSG_T.DSPTCH_TELNO IS '발신전화번호';
COMMENT ON COLUMN TB_TELNO_SMS_MSG_T.RCPTN_TELNO IS '수신전화번호';
COMMENT ON COLUMN TB_TELNO_SMS_MSG_T.DSPTCH_DT IS '발신일시';
COMMENT ON COLUMN TB_TELNO_SMS_MSG_T.MSG_CN_HASH_VL IS '메시지내용해시값';
COMMENT ON COLUMN TB_TELNO_SMS_MSG_T.SPAM_YN IS '스팸여부';
COMMENT ON COLUMN TB_TELNO_SMS_MSG_T.SENTMT_CD IS '감성코드';
COMMENT ON COLUMN TB_TELNO_SMS_MSG_T.ACNT_INCL_YN IS '계정포함여부';
COMMENT ON COLUMN TB_TELNO_SMS_MSG_T.URL_INCL_YN IS 'URL포함여부';
COMMENT ON COLUMN TB_TELNO_SMS_MSG_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_TELNO_SMS_MSG_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_TELNO_SMS_MSG_T IS '전화번호SMS메시지내역';

CREATE UNIQUE INDEX TB_TELNO_SMS_MSG_T_PK ON TB_TELNO_SMS_MSG_T
( MSG_SN );

ALTER TABLE TB_TELNO_SMS_MSG_T
 ADD CONSTRAINT TB_TELNO_SMS_MSG_T_PK PRIMARY KEY 
 USING INDEX TB_TELNO_SMS_MSG_T_PK;

-- 가입내역테이블
CREATE TABLE TB_TELNO_JOIN_T
(
    JOIN_SN    BIGSERIAL NOT NULL,
    TELNO    varchar(11) NOT NULL,
    JOIN_DT    timestamp with time zone,
    CNCLTN_DT    timestamp with time zone,
    SBSR_NM    varchar(100),
    ENRRNO    varchar(256),
    TLCMCO_NM    varchar(100),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_TELNO_JOIN_T.JOIN_SN IS '가입일련번호';
COMMENT ON COLUMN TB_TELNO_JOIN_T.TELNO IS '전화번호';
COMMENT ON COLUMN TB_TELNO_JOIN_T.JOIN_DT IS '가입일시';
COMMENT ON COLUMN TB_TELNO_JOIN_T.CNCLTN_DT IS '해지일시';
COMMENT ON COLUMN TB_TELNO_JOIN_T.SBSR_NM IS '가입자명';
COMMENT ON COLUMN TB_TELNO_JOIN_T.ENRRNO IS '암호화주민등록번호';
COMMENT ON COLUMN TB_TELNO_JOIN_T.TLCMCO_NM IS '통신사명';
COMMENT ON COLUMN TB_TELNO_JOIN_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_TELNO_JOIN_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_TELNO_JOIN_T IS '전화번호가입내역';

CREATE UNIQUE INDEX TB_TELNO_JOIN_T_PK ON TB_TELNO_JOIN_T
( JOIN_SN );

ALTER TABLE TB_TELNO_JOIN_T
 ADD CONSTRAINT TB_TELNO_JOIN_T_PK PRIMARY KEY 
 USING INDEX TB_TELNO_JOIN_T_PK;

-- 채팅메시지내역 테이블
CREATE TABLE TB_CTT_MSG_T
(
    MSG_SN    BIGSERIAL NOT NULL,
    APP_NM    varchar(300) NOT NULL,
    CNVRS_RM_ID    varchar(200),
    SNDPTY_ID    varchar(200),
    DSPTCH_DT    timestamp with time zone NOT NULL,
    MSG_CN_HASH_VL    varchar(64),
    BACNT_INCL_YN    character(1) DEFAULT 'N',
    URL_INCL_YN    character(1) DEFAULT 'N',
    SENTMT_CD    varchar(20),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_CTT_MSG_T.MSG_SN IS '메시지일련번호';
COMMENT ON COLUMN TB_CTT_MSG_T.APP_NM IS '앱명';
COMMENT ON COLUMN TB_CTT_MSG_T.CNVRS_RM_ID IS '대화방아이디';
COMMENT ON COLUMN TB_CTT_MSG_T.SNDPTY_ID IS '발신자아이디';
COMMENT ON COLUMN TB_CTT_MSG_T.DSPTCH_DT IS '발신일시';
COMMENT ON COLUMN TB_CTT_MSG_T.MSG_CN_HASH_VL IS '메시지내용해시값';
COMMENT ON COLUMN TB_CTT_MSG_T.BACNT_INCL_YN IS '계좌포함여부';
COMMENT ON COLUMN TB_CTT_MSG_T.URL_INCL_YN IS 'URL포함여부';
COMMENT ON COLUMN TB_CTT_MSG_T.SENTMT_CD IS '감성코드';
COMMENT ON COLUMN TB_CTT_MSG_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_CTT_MSG_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_CTT_MSG_T IS '채팅메시지내역';

CREATE UNIQUE INDEX TB_CTT_MSG_T_PK ON TB_CTT_MSG_T
( MSG_SN );

ALTER TABLE TB_CTT_MSG_T
 ADD CONSTRAINT TB_CTT_MSG_T_PK PRIMARY KEY 
 USING INDEX TB_CTT_MSG_T_PK;

-- ============================================================
-- 3.7 차량/이동 도메인
-- 차량, 번호판인식, 소유관계
-- ============================================================

-- 차량기본 테이블
CREATE TABLE TB_VHCL_M
(
    VHCL_NO    varchar(13) NOT NULL,
    CARMDL_NM    varchar(100),
    VHCL_MDL_NM    varchar(100),
    COLR_NM    varchar(300),
    OWNR_NM    varchar(100),
    REG_YMD    character(8),
    RBBY_YN    character(1) DEFAULT 'N',
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SRC_DMN_ADDR    varchar(200),
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_VHCL_M.VHCL_NO IS '차량번호';
COMMENT ON COLUMN TB_VHCL_M.CARMDL_NM IS '차종명';
COMMENT ON COLUMN TB_VHCL_M.VHCL_MDL_NM IS '차량모델명';
COMMENT ON COLUMN TB_VHCL_M.COLR_NM IS '색상명';
COMMENT ON COLUMN TB_VHCL_M.OWNR_NM IS '소유자명';
COMMENT ON COLUMN TB_VHCL_M.REG_YMD IS '등록일자';
COMMENT ON COLUMN TB_VHCL_M.RBBY_YN IS '도난여부';
COMMENT ON COLUMN TB_VHCL_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_VHCL_M.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_VHCL_M.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_VHCL_M.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_VHCL_M.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_VHCL_M.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_VHCL_M.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_VHCL_M IS '차량기본';

CREATE UNIQUE INDEX TB_VHCL_M_PK ON TB_VHCL_M
( VHCL_NO );

ALTER TABLE TB_VHCL_M
 ADD CONSTRAINT TB_VHCL_M_PK PRIMARY KEY 
 USING INDEX TB_VHCL_M_PK;

-- 번호판인식이벤트내역
CREATE TABLE TB_VHCL_NOPLT_RECG_EVT_T
(
    RCGN_SN    BIGSERIAL NOT NULL,
    VHCL_NO    varchar(13) NOT NULL,
    RCGN_DT    timestamp with time zone NOT NULL,
    LAT    numeric(12,10),
    LOT    numeric(13,10),
    CCTV_ID    varchar(200),
    INST_NM    varchar(200),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SRC_DMN_ADDR    varchar(200),
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.RCGN_SN IS '검정일련번호';
COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.VHCL_NO IS '차량번호';
COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.RCGN_DT IS '검정일시';
COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.LAT IS '위도';
COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.LOT IS '경도';
COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.CCTV_ID IS 'CCTV아이디';
COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.INST_NM IS '기관명';
COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_VHCL_NOPLT_RECG_EVT_T.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_VHCL_NOPLT_RECG_EVT_T IS '차량번호판인식이벤트내역';

CREATE UNIQUE INDEX TB_VHCL_NOPLT_RECG_EVT_T_PK ON TB_VHCL_NOPLT_RECG_EVT_T
( RCGN_SN );

ALTER TABLE TB_VHCL_NOPLT_RECG_EVT_T
 ADD CONSTRAINT TB_VHCL_NOPLT_RECG_EVT_T_PK PRIMARY KEY 
 USING INDEX TB_VHCL_NOPLT_RECG_EVT_T_PK;

-- 차량소유자관계내역 테이블
CREATE TABLE TB_VHCL_OWNR_REL_T
(
    REL_SN    BIGSERIAL NOT NULL,
    VHCL_NO    varchar(13) NOT NULL,
    OWNR_TYP_CD    varchar(20) NOT NULL,
    VHCL_POSS_REL_ID    varchar(50),
    INST_ID    varchar(200),
    VLD_BGNG_DT    timestamp with time zone,
    VLD_END_DT    timestamp with time zone,
    REG_NO    varchar(50),
    REG_INST_NM    varchar(200),
    CFRT    numeric(5,3) DEFAULT 1.000,
    VRFC_YN    character(1) DEFAULT 'N',
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT    timestamp with time zone,
    USER_ID    varchar(20)
);

COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.REL_SN IS '관계일련번호';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.VHCL_NO IS '차량번호';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.OWNR_TYP_CD IS '소유자타입코드';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.VHCL_POSS_REL_ID IS '차량소유관계아이디';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.INST_ID IS '기관아이디';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.VLD_BGNG_DT IS '유효시작일시';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.VLD_END_DT IS '유효종료일시';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.REG_NO IS '등록번호';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.REG_INST_NM IS '등록기관명';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.CFRT IS '신뢰도';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.VRFC_YN IS '검증여부';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.MDFCN_DT IS '수정일시';
COMMENT ON COLUMN TB_VHCL_OWNR_REL_T.USER_ID IS '사용자아이디';

COMMENT ON TABLE TB_VHCL_OWNR_REL_T IS '차량소유자관계내역';

CREATE UNIQUE INDEX TB_VHCL_OWNR_REL_T_PK ON TB_VHCL_OWNR_REL_T
( REL_SN );

ALTER TABLE TB_VHCL_OWNR_REL_T
 ADD CONSTRAINT TB_VHCL_OWNR_REL_T_PK PRIMARY KEY 
 USING INDEX TB_VHCL_OWNR_REL_T_PK;

-- ============================================================
-- 3.8 위치/지리 도메인
-- 위치정보 및 이동경로
-- ============================================================

-- 위치기본 테이블
CREATE TABLE TB_PSTN_M
(
    PSTN_SN    BIGSERIAL NOT NULL,
    PSTN_ID    varchar(50) NOT NULL,
    PSTN_TYP_CD    varchar(20) NOT NULL,
    ROAD_NM_ADDR    varchar(200),
    LAT    numeric(12,10),
    LOT    numeric(13,10),
    PLC_NM    varchar(100),
    CTPV_NM    varchar(40),
    SGG_NM    varchar(40),
    BSST_NM    varchar(256),
    BSST_ADDR    varchar(300),
    TLCMCO_NM    varchar(100),
    CCTV_ID    varchar(200),
    CCTV_NM    varchar(100),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SRC_DMN_ADDR    varchar(200),
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_PSTN_M.PSTN_SN IS '위치일련번호';
COMMENT ON COLUMN TB_PSTN_M.PSTN_ID IS '위치아이디';
COMMENT ON COLUMN TB_PSTN_M.PSTN_TYP_CD IS '위치타입코드';
COMMENT ON COLUMN TB_PSTN_M.ROAD_NM_ADDR IS '도로명주소';
COMMENT ON COLUMN TB_PSTN_M.LAT IS '위도';
COMMENT ON COLUMN TB_PSTN_M.LOT IS '경도';
COMMENT ON COLUMN TB_PSTN_M.PLC_NM IS '장소명';
COMMENT ON COLUMN TB_PSTN_M.CTPV_NM IS '시도명';
COMMENT ON COLUMN TB_PSTN_M.SGG_NM IS '시군구명';
COMMENT ON COLUMN TB_PSTN_M.BSST_NM IS '기지국명';
COMMENT ON COLUMN TB_PSTN_M.BSST_ADDR IS '기지국주소';
COMMENT ON COLUMN TB_PSTN_M.TLCMCO_NM IS '통신사명';
COMMENT ON COLUMN TB_PSTN_M.CCTV_ID IS 'CCTV아이디';
COMMENT ON COLUMN TB_PSTN_M.CCTV_NM IS 'CCTV명';
COMMENT ON COLUMN TB_PSTN_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_PSTN_M.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_PSTN_M.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_PSTN_M.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_PSTN_M.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_PSTN_M.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_PSTN_M.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_PSTN_M IS '위치기본';

CREATE UNIQUE INDEX TB_PSTN_M_PK ON TB_PSTN_M
( PSTN_SN );

ALTER TABLE TB_PSTN_M
 ADD CONSTRAINT TB_PSTN_M_PK PRIMARY KEY 
 USING INDEX TB_PSTN_M_PK;

-- 모바일위치이벤트내역 테이블
CREATE TABLE TB_MOBL_PSTN_EVT_T
(
    PSTN_EVT_SN    BIGSERIAL NOT NULL,
    TELNO    varchar(11) NOT NULL,
    INCDNT_OCRN_YMD    character(8) NOT NULL,
    EVT_TYP_NM    varchar(50),
    BSST_NM    varchar(256),
    BSST_ADDR    varchar(300),
    BSST_LAT    numeric(16,10),
    BSST_LOT    numeric(13,10),
    TLCMCO_NM    varchar(100),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SRC_DMN_ADDR    varchar(200),
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.PSTN_EVT_SN IS '위치이벤트일련번호';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.TELNO IS '전화번호';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.INCDNT_OCRN_YMD IS '사건발생일자';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.EVT_TYP_NM IS '이벤트타입명';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.BSST_NM IS '기지국명';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.BSST_ADDR IS '기지국주소';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.BSST_LAT IS '기지국위도';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.BSST_LOT IS '기지국경도';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.TLCMCO_NM IS '통신사명';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_MOBL_PSTN_EVT_T.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_MOBL_PSTN_EVT_T IS '모바일위치이벤트내역';

CREATE UNIQUE INDEX TB_MOBL_PSTN_EVT_T_PK ON TB_MOBL_PSTN_EVT_T
( PSTN_EVT_SN );

ALTER TABLE TB_MOBL_PSTN_EVT_T
 ADD CONSTRAINT TB_MOBL_PSTN_EVT_T_PK PRIMARY KEY 
 USING INDEX TB_MOBL_PSTN_EVT_T_PK;

-- 교통카드이용내역 테이블
CREATE TABLE TB_TRFC_CARD_MVMN_T
(
    MVMN_SN    BIGSERIAL NOT NULL,
    CARD_NO    varchar(20) NOT NULL,
    USE_DT    timestamp with time zone NOT NULL,
    DPPL_NM    varchar(300),
    DEST_NM    varchar(200),
    VHCL_NO    varchar(13),
    FARE_AMT    numeric(15),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_TRFC_CARD_MVMN_T.MVMN_SN IS '이동일련번호';
COMMENT ON COLUMN TB_TRFC_CARD_MVMN_T.CARD_NO IS '카드번호';
COMMENT ON COLUMN TB_TRFC_CARD_MVMN_T.USE_DT IS '사용일시';
COMMENT ON COLUMN TB_TRFC_CARD_MVMN_T.DPPL_NM IS '출발지명';
COMMENT ON COLUMN TB_TRFC_CARD_MVMN_T.DEST_NM IS '도착지명';
COMMENT ON COLUMN TB_TRFC_CARD_MVMN_T.VHCL_NO IS '차량번호';
COMMENT ON COLUMN TB_TRFC_CARD_MVMN_T.FARE_AMT IS '운임금액';
COMMENT ON COLUMN TB_TRFC_CARD_MVMN_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_TRFC_CARD_MVMN_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_TRFC_CARD_MVMN_T IS '교통카드이동내역';

CREATE UNIQUE INDEX TB_TRFC_CARD_MVMN_T_PK ON TB_TRFC_CARD_MVMN_T
( MVMN_SN );

ALTER TABLE TB_TRFC_CARD_MVMN_T
 ADD CONSTRAINT TB_TRFC_CARD_MVMN_T_PK PRIMARY KEY 
 USING INDEX TB_TRFC_CARD_MVMN_T_PK;

-- ATM기본 테이블
CREATE TABLE TB_ATM_M
(
    ATM_SN    BIGSERIAL NOT NULL,
    ATM_MNG_NO    varchar(20) NOT NULL,
    BANK_NM    varchar(100),
    BANK_CD    varchar(30),
    PSTN_ID    varchar(50),
    INST_ADDR    varchar(200),
    LAT    numeric(12,10),
    LOT    numeric(13,10),
    OTDR_INSTL_YN    character(1) DEFAULT 'N',
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT    timestamp with time zone,
    USER_ID    varchar(20),
    SRC_DMN_ADDR    varchar(200),
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_ATM_M.ATM_SN IS 'ATM일련번호';
COMMENT ON COLUMN TB_ATM_M.ATM_MNG_NO IS 'ATM관리번호';
COMMENT ON COLUMN TB_ATM_M.BANK_NM IS '은행명';
COMMENT ON COLUMN TB_ATM_M.BANK_CD IS '은행코드';
COMMENT ON COLUMN TB_ATM_M.PSTN_ID IS '위치아이디';
COMMENT ON COLUMN TB_ATM_M.INST_ADDR IS '기관주소';
COMMENT ON COLUMN TB_ATM_M.LAT IS '위도';
COMMENT ON COLUMN TB_ATM_M.LOT IS '경도';
COMMENT ON COLUMN TB_ATM_M.OTDR_INSTL_YN IS '실외설치여부';
COMMENT ON COLUMN TB_ATM_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_ATM_M.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_ATM_M.MDFCN_DT IS '수정일시';
COMMENT ON COLUMN TB_ATM_M.USER_ID IS '사용자아이디';
COMMENT ON COLUMN TB_ATM_M.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_ATM_M.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_ATM_M.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_ATM_M.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_ATM_M.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_ATM_M IS 'ATM기본';

CREATE UNIQUE INDEX TB_ATM_M_PK ON TB_ATM_M
( ATM_SN );

ALTER TABLE TB_ATM_M
 ADD CONSTRAINT TB_ATM_M_PK PRIMARY KEY 
 USING INDEX TB_ATM_M_PK;

-- ============================================================
-- 3.9 디지털 도메인
-- 디지털 식별자 및 행위정보
-- ============================================================

-- IP주소기본 테이블
CREATE TABLE TB_IP_ADDR_M
(
    IP_SN    BIGSERIAL NOT NULL,
    IP_ADDR    varchar(15) NOT NULL,
    IP_VER_CD    character(4) DEFAULT 'IPv4' NOT NULL,
    ITNT_SRVC_OFFR_NM    varchar(200),
    SLFCT_SYS_NO    varchar(20),
    NTN_CD    character(3),
    CTY_NM    varchar(200),
    VPN_YN    character(1) DEFAULT 'N',
    TOR_YN    character(1) DEFAULT 'N',
    PROXY_YN    character(1) DEFAULT 'N',
    HOSTING_YN    character(1) DEFAULT 'N',
    ABUSE_SCR    numeric(3),
    RISK_GRD_CD    numeric(3),
    FRST_DSCV_DT    timestamp with time zone,
    LAST_CLSF_DT    timestamp with time zone,
    CFRT    numeric(5,3) DEFAULT 1.000,
    VRFC_YN    character(1) DEFAULT 'N',
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT    timestamp with time zone,
    USER_ID    varchar(20),
    SRC_DMN_ADDR    varchar(200),
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_IP_ADDR_M.IP_SN IS 'IP일련번호';
COMMENT ON COLUMN TB_IP_ADDR_M.IP_ADDR IS 'IP주소';
COMMENT ON COLUMN TB_IP_ADDR_M.IP_VER_CD IS 'IP버전코드';
COMMENT ON COLUMN TB_IP_ADDR_M.ITNT_SRVC_OFFR_NM IS '인터넷서비스제공자명';
COMMENT ON COLUMN TB_IP_ADDR_M.SLFCT_SYS_NO IS '자율시스템번호';
COMMENT ON COLUMN TB_IP_ADDR_M.NTN_CD IS '국가코드';
COMMENT ON COLUMN TB_IP_ADDR_M.CTY_NM IS '도시명';
COMMENT ON COLUMN TB_IP_ADDR_M.VPN_YN IS 'VPN여부';
COMMENT ON COLUMN TB_IP_ADDR_M.TOR_YN IS 'TOR여부';
COMMENT ON COLUMN TB_IP_ADDR_M.PROXY_YN IS '프록시여부';
COMMENT ON COLUMN TB_IP_ADDR_M.HOSTING_YN IS '호스팅여부';
COMMENT ON COLUMN TB_IP_ADDR_M.ABUSE_SCR IS '악용점수';
COMMENT ON COLUMN TB_IP_ADDR_M.RISK_GRD_CD IS '위험등급코드';
COMMENT ON COLUMN TB_IP_ADDR_M.FRST_DSCV_DT IS '최초발견일시';
COMMENT ON COLUMN TB_IP_ADDR_M.LAST_CLSF_DT IS '최종분류일시';
COMMENT ON COLUMN TB_IP_ADDR_M.CFRT IS '신뢰도';
COMMENT ON COLUMN TB_IP_ADDR_M.VRFC_YN IS '검증여부';
COMMENT ON COLUMN TB_IP_ADDR_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_IP_ADDR_M.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_IP_ADDR_M.MDFCN_DT IS '수정일시';
COMMENT ON COLUMN TB_IP_ADDR_M.USER_ID IS '사용자아이디';
COMMENT ON COLUMN TB_IP_ADDR_M.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_IP_ADDR_M.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_IP_ADDR_M.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_IP_ADDR_M.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_IP_ADDR_M.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_IP_ADDR_M IS 'IP주소기본';

CREATE UNIQUE INDEX TB_IP_ADDR_M_PK ON TB_IP_ADDR_M
( IP_SN );

ALTER TABLE TB_IP_ADDR_M
 ADD CONSTRAINT TB_IP_ADDR_M_PK PRIMARY KEY 
 USING INDEX TB_IP_ADDR_M_PK;

-- 웹도메인기본 테이블
CREATE TABLE TB_WEB_DMN_M
(
    URL_ADDR    varchar(2000) NOT NULL,
    DMN_ADDR    varchar(200),
    SITE_TYP_CD    character(3),
    MLGN_YN    character(1) DEFAULT 'N',
    IP_ADDR    varchar(15),
    PGE_HASH_VL    varchar(64),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_WEB_DMN_M.URL_ADDR IS 'URL주소';
COMMENT ON COLUMN TB_WEB_DMN_M.DMN_ADDR IS '도메인주소';
COMMENT ON COLUMN TB_WEB_DMN_M.SITE_TYP_CD IS '사이트타입코드';
COMMENT ON COLUMN TB_WEB_DMN_M.MLGN_YN IS '악성여부';
COMMENT ON COLUMN TB_WEB_DMN_M.IP_ADDR IS 'IP주소';
COMMENT ON COLUMN TB_WEB_DMN_M.PGE_HASH_VL IS '페이지해시값';
COMMENT ON COLUMN TB_WEB_DMN_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_WEB_DMN_M.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_WEB_DMN_M IS '웹도메인기본';

CREATE UNIQUE INDEX TB_WEB_DMN_M_PK ON TB_WEB_DMN_M
( URL_ADDR );

ALTER TABLE TB_WEB_DMN_M
 ADD CONSTRAINT TB_WEB_DMN_M_PK PRIMARY KEY 
 USING INDEX TB_WEB_DMN_M_PK;

-- 웹악성지표내역 테이블
CREATE TABLE TB_WEB_MLGN_IDCT_T
(
    IDCT_SN    BIGSERIAL NOT NULL,
    URL_ADDR    varchar(2000) NOT NULL,
    RISK_GRD_CD    numeric(3) NOT NULL,
    SGNT_KYWD_CN    varchar(500),
    DTCN_DT    timestamp with time zone,
    RGTR_NM    varchar(100),
    INST_NM    varchar(200),
    DMN_REG_DT    timestamp with time zone,
    DMN_EXPRY_DT    timestamp with time zone,
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_WEB_MLGN_IDCT_T.IDCT_SN IS '지표일련번호';
COMMENT ON COLUMN TB_WEB_MLGN_IDCT_T.URL_ADDR IS 'URL주소';
COMMENT ON COLUMN TB_WEB_MLGN_IDCT_T.RISK_GRD_CD IS '위험등급코드';
COMMENT ON COLUMN TB_WEB_MLGN_IDCT_T.SGNT_KYWD_CN IS '시그니처키워드내용';
COMMENT ON COLUMN TB_WEB_MLGN_IDCT_T.DTCN_DT IS '탐지일시';
COMMENT ON COLUMN TB_WEB_MLGN_IDCT_T.RGTR_NM IS '등록자명';
COMMENT ON COLUMN TB_WEB_MLGN_IDCT_T.INST_NM IS '기관명';
COMMENT ON COLUMN TB_WEB_MLGN_IDCT_T.DMN_REG_DT IS '도메인등록일시';
COMMENT ON COLUMN TB_WEB_MLGN_IDCT_T.DMN_EXPRY_DT IS '도메인만료일시';
COMMENT ON COLUMN TB_WEB_MLGN_IDCT_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_WEB_MLGN_IDCT_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_WEB_MLGN_IDCT_T IS '웹악성지표내역';

CREATE UNIQUE INDEX TB_WEB_MLGN_IDCT_T_PK ON TB_WEB_MLGN_IDCT_T
( IDCT_SN );

ALTER TABLE TB_WEB_MLGN_IDCT_T
 ADD CONSTRAINT TB_WEB_MLGN_IDCT_T_PK PRIMARY KEY 
 USING INDEX TB_WEB_MLGN_IDCT_T_PK;

-- 시스템로그인이벤트내역 테이블
CREATE TABLE TB_SYS_LGN_EVT_T
(
    LGN_SN    BIGSERIAL NOT NULL,
    IP_ADDR    varchar(15) NOT NULL,
    CNTN_DT    timestamp with time zone NOT NULL,
    ACTN_CD    varchar(20),
    USER_AGNT_CN    varchar(4000),
    STTS_CD    numeric(3),
    TRSM_BYTE_CNT    numeric(10),
    RCPTN_BYTE_CNT    numeric(10),
    TRGT_URL_ADDR    varchar(2000),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SRC_DMN_ADDR    varchar(200),
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_SYS_LGN_EVT_T.LGN_SN IS '로그인일련번호';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.IP_ADDR IS 'IP주소';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.CNTN_DT IS '접속일시';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.ACTN_CD IS '조치코드';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.USER_AGNT_CN IS '사용자에이전트내용';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.STTS_CD IS '상태코드';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.TRSM_BYTE_CNT IS '전송바이트수';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.RCPTN_BYTE_CNT IS '수신바이트수';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.TRGT_URL_ADDR IS '대상URL주소';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_SYS_LGN_EVT_T.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_SYS_LGN_EVT_T IS '시스템로그인이벤트내역';

CREATE UNIQUE INDEX TB_SYS_LGN_EVT_T_PK ON TB_SYS_LGN_EVT_T
( LGN_SN );

ALTER TABLE TB_SYS_LGN_EVT_T
 ADD CONSTRAINT TB_SYS_LGN_EVT_T_PK PRIMARY KEY 
 USING INDEX TB_SYS_LGN_EVT_T_PK;

-- 디지털파일목록기본 테이블
CREATE TABLE TB_DGTL_FILE_LIST_M
(
    FILE_ID    varchar(20) NOT NULL,
    FILE_HASH_SHA256_VL    varchar(500) NOT NULL,
    FILE_HASH_MD5_VL    varchar(500),
    FILE_NM    varchar(300),
    FILE_SZ_BYTE_CNT    numeric(10),
    MIME_TYP_NM    varchar(100),
    EVDC_ID    varchar(50),
    SRC_ID    varchar(200),
    SRC_DMN_ADDR    varchar(200) DEFAULT 'DIGITAL',
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_DGTL_FILE_LIST_M.FILE_ID IS '파일아이디';
COMMENT ON COLUMN TB_DGTL_FILE_LIST_M.FILE_HASH_SHA256_VL IS '파일해시SHA256값';
COMMENT ON COLUMN TB_DGTL_FILE_LIST_M.FILE_HASH_MD5_VL IS '파일해시MD5값';
COMMENT ON COLUMN TB_DGTL_FILE_LIST_M.FILE_NM IS '파일명';
COMMENT ON COLUMN TB_DGTL_FILE_LIST_M.FILE_SZ_BYTE_CNT IS '파일크기바이트수';
COMMENT ON COLUMN TB_DGTL_FILE_LIST_M.MIME_TYP_NM IS 'MIME타입명';
COMMENT ON COLUMN TB_DGTL_FILE_LIST_M.EVDC_ID IS '증거아이디';
COMMENT ON COLUMN TB_DGTL_FILE_LIST_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_DGTL_FILE_LIST_M.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_DGTL_FILE_LIST_M.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_DGTL_FILE_LIST_M.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_DGTL_FILE_LIST_M.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_DGTL_FILE_LIST_M.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_DGTL_FILE_LIST_M IS '디지털파일목록기본';

CREATE UNIQUE INDEX TB_DGTL_FILE_LIST_M_PK ON TB_DGTL_FILE_LIST_M
( FILE_ID );

ALTER TABLE TB_DGTL_FILE_LIST_M
 ADD CONSTRAINT TB_DGTL_FILE_LIST_M_PK PRIMARY KEY 
 USING INDEX TB_DGTL_FILE_LIST_M_PK;

-- 디지털아이디기본 테이블
CREATE TABLE TB_DGTL_ID_M
(
    ID_SN    BIGSERIAL NOT NULL,
    ACS_ACNT_ID    varchar(20) NOT NULL,
    PLFM_NM    varchar(100) NOT NULL,
    ID_TYP_CD    varchar(20),
    PRFL_URL_ADDR    varchar(500),
    ACTVTN_YN    character(1) DEFAULT 'Y',
    RLNM_VL    varchar(100),
    CFRT    numeric(5,3) DEFAULT 1.000,
    VRFC_YN    character(1) DEFAULT 'N',
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT    timestamp with time zone,
    USER_ID    varchar(20),
    SRC_DMN_ADDR    varchar(200),
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ANMT_ID_INFC_YN    character(1) DEFAULT 'N'
);

COMMENT ON COLUMN TB_DGTL_ID_M.ID_SN IS '아이디일련번호';
COMMENT ON COLUMN TB_DGTL_ID_M.ACS_ACNT_ID IS '접근계정아이디';
COMMENT ON COLUMN TB_DGTL_ID_M.PLFM_NM IS '플랫폼명';
COMMENT ON COLUMN TB_DGTL_ID_M.ID_TYP_CD IS '아이디타입코드';
COMMENT ON COLUMN TB_DGTL_ID_M.PRFL_URL_ADDR IS '프로필URL주소';
COMMENT ON COLUMN TB_DGTL_ID_M.ACTVTN_YN IS '활성여부';
COMMENT ON COLUMN TB_DGTL_ID_M.RLNM_VL IS '실명값';
COMMENT ON COLUMN TB_DGTL_ID_M.CFRT IS '신뢰도';
COMMENT ON COLUMN TB_DGTL_ID_M.VRFC_YN IS '검증여부';
COMMENT ON COLUMN TB_DGTL_ID_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_DGTL_ID_M.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_DGTL_ID_M.MDFCN_DT IS '수정일시';
COMMENT ON COLUMN TB_DGTL_ID_M.USER_ID IS '사용자아이디';
COMMENT ON COLUMN TB_DGTL_ID_M.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_DGTL_ID_M.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_DGTL_ID_M.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_DGTL_ID_M.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_DGTL_ID_M.RCRD_MDFCN_DT IS '레코드수정일시';
COMMENT ON COLUMN TB_DGTL_ID_M.ANMT_ID_INFC_YN IS '익명아이디추론여부';

COMMENT ON TABLE TB_DGTL_ID_M IS '디지털아이디기본';

CREATE UNIQUE INDEX TB_DGTL_ID_M_PK ON TB_DGTL_ID_M
( ID_SN );

ALTER TABLE TB_DGTL_ID_M
 ADD CONSTRAINT TB_DGTL_ID_M_PK PRIMARY KEY 
 USING INDEX TB_DGTL_ID_M_PK;

-- 이메일주소기본 테이블
CREATE TABLE TB_EML_ADDR_M
(
    EML_SN    BIGSERIAL NOT NULL,
    EML_ADDR    varchar(320) NOT NULL,
    DMN_ADDR    varchar(200),
    SPLR_NM    varchar(100),
    ONTM_EML_YN    character(1) DEFAULT 'N',
    VLD_YN    character(1) DEFAULT 'Y',
    CFRT    numeric(5,3) DEFAULT 1.000,
    VRFC_YN    character(1) DEFAULT 'N',
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT    timestamp with time zone,
    USER_ID    varchar(20)
);

COMMENT ON COLUMN TB_EML_ADDR_M.EML_SN IS '이메일일련번호';
COMMENT ON COLUMN TB_EML_ADDR_M.EML_ADDR IS '이메일주소';
COMMENT ON COLUMN TB_EML_ADDR_M.DMN_ADDR IS '도메인주소';
COMMENT ON COLUMN TB_EML_ADDR_M.SPLR_NM IS '공급자명';
COMMENT ON COLUMN TB_EML_ADDR_M.ONTM_EML_YN IS '일회성이메일여부';
COMMENT ON COLUMN TB_EML_ADDR_M.VLD_YN IS '유효여부';
COMMENT ON COLUMN TB_EML_ADDR_M.CFRT IS '신뢰도';
COMMENT ON COLUMN TB_EML_ADDR_M.VRFC_YN IS '검증여부';
COMMENT ON COLUMN TB_EML_ADDR_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_EML_ADDR_M.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_EML_ADDR_M.MDFCN_DT IS '수정일시';
COMMENT ON COLUMN TB_EML_ADDR_M.USER_ID IS '사용자아이디';

COMMENT ON TABLE TB_EML_ADDR_M IS '이메일주소기본';

CREATE UNIQUE INDEX TB_EML_ADDR_M_PK ON TB_EML_ADDR_M
( EML_SN );

ALTER TABLE TB_EML_ADDR_M
 ADD CONSTRAINT TB_EML_ADDR_M_PK PRIMARY KEY 
 USING INDEX TB_EML_ADDR_M_PK;

-- 기기기본 테이블
CREATE TABLE TB_ISTR_M
(
    ISTR_SN    BIGSERIAL NOT NULL,
    ISTR_ID    varchar(100) NOT NULL,
    ISTR_TYP_CD    varchar(20),
    IMEI_VL    varchar(20),
    MAC_ADDR    varchar(17),
    MDL_NM    varchar(100),
    OS_NM    varchar(300),
    VER_NO    varchar(50),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT    timestamp with time zone,
    USER_ID    varchar(20),
    SRC_DMN_ADDR    varchar(200),
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_ISTR_M.ISTR_SN IS '기기일련번호';
COMMENT ON COLUMN TB_ISTR_M.ISTR_ID IS '기기아이디';
COMMENT ON COLUMN TB_ISTR_M.ISTR_TYP_CD IS '기기타입코드';
COMMENT ON COLUMN TB_ISTR_M.IMEI_VL IS 'IMEI값';
COMMENT ON COLUMN TB_ISTR_M.MAC_ADDR IS 'MAC주소';
COMMENT ON COLUMN TB_ISTR_M.MDL_NM IS '모델명';
COMMENT ON COLUMN TB_ISTR_M.OS_NM IS '운영체제명';
COMMENT ON COLUMN TB_ISTR_M.VER_NO IS '버전번호';
COMMENT ON COLUMN TB_ISTR_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_ISTR_M.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_ISTR_M.MDFCN_DT IS '수정일시';
COMMENT ON COLUMN TB_ISTR_M.USER_ID IS '사용자아이디';
COMMENT ON COLUMN TB_ISTR_M.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_ISTR_M.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_ISTR_M.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_ISTR_M.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_ISTR_M.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_ISTR_M IS '기기기본';

CREATE UNIQUE INDEX TB_ISTR_M_PK ON TB_ISTR_M
( ISTR_SN );

ALTER TABLE TB_ISTR_M
 ADD CONSTRAINT TB_ISTR_M_PK PRIMARY KEY 
 USING INDEX TB_ISTR_M_PK;

-- ============================================================
-- 3.10 OSINT 도메인
-- 공개정보 기반 평판정보
-- ============================================================

-- OSINTIP평판내역 테이블
CREATE TABLE TB_OSINT_IP_RPUTTN_T
(
    RPTP_SN    BIGSERIAL NOT NULL,
    IP_ADDR    varchar(15) NOT NULL,
    SRC_ID    varchar(200) NOT NULL,
    INQ_DT    timestamp with time zone NOT NULL,
    VPN_YN    character(1) DEFAULT 'N',
    TOR_YN    character(1) DEFAULT 'N',
    PROXY_YN    character(1) DEFAULT 'N',
    HOSTING_YN    character(1) DEFAULT 'N',
    ABUSE_SCR    numeric(3),
    ITNT_SRVC_OFFR_NM    varchar(200),
    SLFCT_SYS_NO    varchar(20),
    NTN_CD    character(3),
    RAW_JSON_CN    varchar(4000),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.RPTP_SN IS '보고서일련번호';
COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.IP_ADDR IS 'IP주소';
COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.INQ_DT IS '조회일시';
COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.VPN_YN IS 'VPN여부';
COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.TOR_YN IS 'TOR여부';
COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.PROXY_YN IS '프록시여부';
COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.HOSTING_YN IS '호스팅여부';
COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.ABUSE_SCR IS '악용점수';
COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.ITNT_SRVC_OFFR_NM IS '인터넷서비스제공자명';
COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.SLFCT_SYS_NO IS '자율시스템번호';
COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.NTN_CD IS '국가코드';
COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.RAW_JSON_CN IS '원시JSON내용';
COMMENT ON COLUMN TB_OSINT_IP_RPUTTN_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_OSINT_IP_RPUTTN_T IS 'OSINTIP평판내역';

CREATE UNIQUE INDEX TB_OSINT_IP_RPUTTN_T_PK ON TB_OSINT_IP_RPUTTN_T
( RPTP_SN );

ALTER TABLE TB_OSINT_IP_RPUTTN_T
 ADD CONSTRAINT TB_OSINT_IP_RPUTTN_T_PK PRIMARY KEY 
 USING INDEX TB_OSINT_IP_RPUTTN_T_PK;

-- OSINT도메인평판내역 테이블
CREATE TABLE TB_OSINT_DMN_RPUTTN_T
(
    RPTP_SN    BIGSERIAL NOT NULL,
    DMN_ADDR    varchar(200) NOT NULL,
    SRC_ID    varchar(200) NOT NULL,
    INQ_DT    timestamp with time zone NOT NULL,
    RISK_GRD_CD    numeric(3),
    MLGN_YN    character(1) DEFAULT 'N',
    REG_INST_NM    varchar(200),
    DMN_REG_DT    timestamp with time zone,
    DMN_EXPRY_DT    timestamp with time zone,
    RGTR_NM    varchar(100),
    RGTR_EML_ADDR    varchar(320),
    INST_NM    varchar(200),
    RAW_JSON_CN    varchar(4000),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.RPTP_SN IS '보고서일련번호';
COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.DMN_ADDR IS '도메인주소';
COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.INQ_DT IS '조회일시';
COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.RISK_GRD_CD IS '위험등급코드';
COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.MLGN_YN IS '악성여부';
COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.REG_INST_NM IS '등록기관명';
COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.DMN_REG_DT IS '도메인등록일시';
COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.DMN_EXPRY_DT IS '도메인만료일시';
COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.RGTR_NM IS '등록자명';
COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.RGTR_EML_ADDR IS '등록자이메일주소';
COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.INST_NM IS '기관명';
COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.RAW_JSON_CN IS '원시JSON내용';
COMMENT ON COLUMN TB_OSINT_DMN_RPUTTN_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_OSINT_DMN_RPUTTN_T IS 'OSINT도메인평판내역';

CREATE UNIQUE INDEX TB_OSINT_DMN_RPUTTN_T_PK ON TB_OSINT_DMN_RPUTTN_T
( RPTP_SN );

ALTER TABLE TB_OSINT_DMN_RPUTTN_T
 ADD CONSTRAINT TB_OSINT_DMN_RPUTTN_T_PK PRIMARY KEY 
 USING INDEX TB_OSINT_DMN_RPUTTN_T_PK;

-- OSINT해시평판내역 테이블
CREATE TABLE TB_OSINT_HASH_RPUTTN_T
(
    RPTP_SN    BIGSERIAL NOT NULL,
    HASH_VL    varchar(100) NOT NULL,
    SRC_ID    varchar(200) NOT NULL,
    INQ_DT    timestamp with time zone NOT NULL,
    MLGN_YN    character(1) DEFAULT 'N',
    DTCN_NOCS    numeric(3),
    TOTL_CNT    numeric(3),
    MLGN_NM    varchar(100),
    FILE_TYP_NM    varchar(300),
    RAW_JSON_CN    varchar(4000),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_OSINT_HASH_RPUTTN_T.RPTP_SN IS '보고서일련번호';
COMMENT ON COLUMN TB_OSINT_HASH_RPUTTN_T.HASH_VL IS '해시값';
COMMENT ON COLUMN TB_OSINT_HASH_RPUTTN_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_OSINT_HASH_RPUTTN_T.INQ_DT IS '조회일시';
COMMENT ON COLUMN TB_OSINT_HASH_RPUTTN_T.MLGN_YN IS '악성여부';
COMMENT ON COLUMN TB_OSINT_HASH_RPUTTN_T.DTCN_NOCS IS '탐지건수';
COMMENT ON COLUMN TB_OSINT_HASH_RPUTTN_T.TOTL_CNT IS '총수';
COMMENT ON COLUMN TB_OSINT_HASH_RPUTTN_T.MLGN_NM IS '악성명';
COMMENT ON COLUMN TB_OSINT_HASH_RPUTTN_T.FILE_TYP_NM IS '파일타입명';
COMMENT ON COLUMN TB_OSINT_HASH_RPUTTN_T.RAW_JSON_CN IS '원시JSON내용';
COMMENT ON COLUMN TB_OSINT_HASH_RPUTTN_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_OSINT_HASH_RPUTTN_T IS 'OSINT해시평판내역';

CREATE UNIQUE INDEX TB_OSINT_HASH_RPUTTN_T_PK ON TB_OSINT_HASH_RPUTTN_T
( RPTP_SN );

ALTER TABLE TB_OSINT_HASH_RPUTTN_T
 ADD CONSTRAINT TB_OSINT_HASH_RPUTTN_T_PK PRIMARY KEY 
 USING INDEX TB_OSINT_HASH_RPUTTN_T_PK;

-- OSINT전화번호평판내역 테이블
CREATE TABLE TB_OSINT_TELNO_RPUTTN_T
(
    RPTP_SN    BIGSERIAL NOT NULL,
    TELNO    varchar(11) NOT NULL,
    SRC_ID    varchar(200) NOT NULL,
    INQ_DT    timestamp with time zone NOT NULL,
    SPAM_CNT    numeric(4) DEFAULT 0,
    CRIM_SE_CD    varchar(5),
    FRST_DCLR_DT    timestamp with time zone,
    LAST_RPT_DT    timestamp with time zone,
    INST_IDNTY_YN    character(1) DEFAULT 'N',
    RAW_JSON_CN    varchar(4000),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_OSINT_TELNO_RPUTTN_T.RPTP_SN IS '보고서일련번호';
COMMENT ON COLUMN TB_OSINT_TELNO_RPUTTN_T.TELNO IS '전화번호';
COMMENT ON COLUMN TB_OSINT_TELNO_RPUTTN_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_OSINT_TELNO_RPUTTN_T.INQ_DT IS '조회일시';
COMMENT ON COLUMN TB_OSINT_TELNO_RPUTTN_T.SPAM_CNT IS '스팸수';
COMMENT ON COLUMN TB_OSINT_TELNO_RPUTTN_T.CRIM_SE_CD IS '범죄구분코드';
COMMENT ON COLUMN TB_OSINT_TELNO_RPUTTN_T.FRST_DCLR_DT IS '최초신고일시';
COMMENT ON COLUMN TB_OSINT_TELNO_RPUTTN_T.LAST_RPT_DT IS '최종보고일시';
COMMENT ON COLUMN TB_OSINT_TELNO_RPUTTN_T.INST_IDNTY_YN IS '기관확인여부';
COMMENT ON COLUMN TB_OSINT_TELNO_RPUTTN_T.RAW_JSON_CN IS '원시JSON내용';
COMMENT ON COLUMN TB_OSINT_TELNO_RPUTTN_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_OSINT_TELNO_RPUTTN_T IS 'OSINT전화번호평판내역';

CREATE UNIQUE INDEX TB_OSINT_TELNO_RPUTTN_T_PK ON TB_OSINT_TELNO_RPUTTN_T
( RPTP_SN );

ALTER TABLE TB_OSINT_TELNO_RPUTTN_T
 ADD CONSTRAINT TB_OSINT_TELNO_RPUTTN_T_PK PRIMARY KEY 
 USING INDEX TB_OSINT_TELNO_RPUTTN_T_PK;

-- OSINT계좌평판내역 테이블
CREATE TABLE TB_OSINT_BACNT_RPUTTN_T
(
    RPTP_SN    BIGSERIAL NOT NULL,
    ACTNO    varchar(20) NOT NULL,
    BANK_CD    varchar(30) NOT NULL,
    SRC_ID    varchar(200) NOT NULL,
    INQ_DT    timestamp with time zone NOT NULL,
    DCLR_NOCS    numeric(10) DEFAULT 0,
    DAM_AMT    numeric(15),
    FRST_DCLR_DT    timestamp with time zone,
    LAST_RPT_DT    timestamp with time zone,
    FRZN_BACNT_YN    character(1) DEFAULT 'N',
    IDNTY_YN    character(1) DEFAULT 'N',
    RAW_JSON_CN    varchar(4000),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_OSINT_BACNT_RPUTTN_T.RPTP_SN IS '보고서일련번호';
COMMENT ON COLUMN TB_OSINT_BACNT_RPUTTN_T.ACTNO IS '계좌번호';
COMMENT ON COLUMN TB_OSINT_BACNT_RPUTTN_T.BANK_CD IS '은행코드';
COMMENT ON COLUMN TB_OSINT_BACNT_RPUTTN_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_OSINT_BACNT_RPUTTN_T.INQ_DT IS '조회일시';
COMMENT ON COLUMN TB_OSINT_BACNT_RPUTTN_T.DCLR_NOCS IS '신고건수';
COMMENT ON COLUMN TB_OSINT_BACNT_RPUTTN_T.DAM_AMT IS '피해금액';
COMMENT ON COLUMN TB_OSINT_BACNT_RPUTTN_T.FRST_DCLR_DT IS '최초신고일시';
COMMENT ON COLUMN TB_OSINT_BACNT_RPUTTN_T.LAST_RPT_DT IS '최종보고일시';
COMMENT ON COLUMN TB_OSINT_BACNT_RPUTTN_T.FRZN_BACNT_YN IS '동결계좌여부';
COMMENT ON COLUMN TB_OSINT_BACNT_RPUTTN_T.IDNTY_YN IS '확인여부';
COMMENT ON COLUMN TB_OSINT_BACNT_RPUTTN_T.RAW_JSON_CN IS '원시JSON내용';
COMMENT ON COLUMN TB_OSINT_BACNT_RPUTTN_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_OSINT_BACNT_RPUTTN_T IS 'OSINT계좌평판내역';

CREATE UNIQUE INDEX TB_OSINT_BACNT_RPUTTN_T_PK ON TB_OSINT_BACNT_RPUTTN_T
( RPTP_SN );

ALTER TABLE TB_OSINT_BACNT_RPUTTN_T
 ADD CONSTRAINT TB_OSINT_BACNT_RPUTTN_T_PK PRIMARY KEY 
 USING INDEX TB_OSINT_BACNT_RPUTTN_T_PK;

-- OSINT지갑평판내역 테이블
CREATE TABLE TB_OSINT_WLET_RPUTTN_T
(
    WLET_SN    BIGSERIAL NOT NULL,
    WLET_ADDR    varchar(200) NOT NULL,
    BLCKCHN_NM    varchar(20) NOT NULL,
    VR_AST_CD    varchar(10),
    EXCHG_NM    varchar(100),
    BLNC    numeric(15),
    RISK_SCR    numeric(5,2),
    KYC_VRFC_YN    character(1) DEFAULT 'N',
    DLNG_NOCS    numeric(10) DEFAULT 0,
    CFRT    numeric(5,3) DEFAULT 1.000,
    VRFC_YN    character(1) DEFAULT 'N',
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT    timestamp with time zone,
    USER_ID    varchar(20),
    SRC_DMN_ADDR    varchar(200),
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.WLET_SN IS '지갑일련번호';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.WLET_ADDR IS '지갑주소';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.BLCKCHN_NM IS '블록체인명';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.VR_AST_CD IS '가상자산코드';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.EXCHG_NM IS '거래소명';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.BLNC IS '잔액';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.RISK_SCR IS '위험점수';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.KYC_VRFC_YN IS 'KYC검증여부';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.DLNG_NOCS IS '거래건수';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.CFRT IS '신뢰도';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.VRFC_YN IS '검증여부';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.MDFCN_DT IS '수정일시';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.USER_ID IS '사용자아이디';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_OSINT_WLET_RPUTTN_T.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_OSINT_WLET_RPUTTN_T IS 'OSINT지갑평판내역';

CREATE UNIQUE INDEX TB_OSINT_WLET_RPUTTN_T_PK ON TB_OSINT_WLET_RPUTTN_T
( WLET_SN );

ALTER TABLE TB_OSINT_WLET_RPUTTN_T
 ADD CONSTRAINT TB_OSINT_WLET_RPUTTN_T_PK PRIMARY KEY 
 USING INDEX TB_OSINT_WLET_RPUTTN_T_PK;

-- OSINT아이디평판내역 테이블
CREATE TABLE TB_OSINT_ID_RPUTTN_T
(
    RPTP_SN    BIGSERIAL NOT NULL,
    ACS_ACNT_ID    varchar(20) NOT NULL,
    PLFM_NM    varchar(100) NOT NULL,
    SRC_ID    varchar(200) NOT NULL,
    INQ_DT    timestamp with time zone NOT NULL,
    DCLR_NOCS    numeric(10) DEFAULT 0,
    ACTVTN_YN    character(1),
    PRFL_URL_ADDR    varchar(500),
    RAW_JSON_CN    varchar(4000),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_OSINT_ID_RPUTTN_T.RPTP_SN IS '보고서일련번호';
COMMENT ON COLUMN TB_OSINT_ID_RPUTTN_T.ACS_ACNT_ID IS '접근계정아이디';
COMMENT ON COLUMN TB_OSINT_ID_RPUTTN_T.PLFM_NM IS '플랫폼명';
COMMENT ON COLUMN TB_OSINT_ID_RPUTTN_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_OSINT_ID_RPUTTN_T.INQ_DT IS '조회일시';
COMMENT ON COLUMN TB_OSINT_ID_RPUTTN_T.DCLR_NOCS IS '신고건수';
COMMENT ON COLUMN TB_OSINT_ID_RPUTTN_T.ACTVTN_YN IS '활성여부';
COMMENT ON COLUMN TB_OSINT_ID_RPUTTN_T.PRFL_URL_ADDR IS '프로필URL주소';
COMMENT ON COLUMN TB_OSINT_ID_RPUTTN_T.RAW_JSON_CN IS '원시JSON내용';
COMMENT ON COLUMN TB_OSINT_ID_RPUTTN_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_OSINT_ID_RPUTTN_T IS 'OSINT아이디평판내역';

CREATE UNIQUE INDEX TB_OSINT_ID_RPUTTN_T_PK ON TB_OSINT_ID_RPUTTN_T
( RPTP_SN );

ALTER TABLE TB_OSINT_ID_RPUTTN_T
 ADD CONSTRAINT TB_OSINT_ID_RPUTTN_T_PK PRIMARY KEY 
 USING INDEX TB_OSINT_ID_RPUTTN_T_PK;

-- OSINT사이트군집기본 테이블
CREATE TABLE TB_OSINT_SITE_CLSTR_M
(
    CLST_ID    varchar(50) NOT NULL,
    CLST_NM    varchar(100),
    SIMHASH_6_4_VL    varchar(64) NOT NULL,
    OGNZ_MBER_CNT    numeric(4) DEFAULT 0,
    RPRS_URL_ADDR    varchar(2000),
    SRC_ID    varchar(200),
    SRC_DMN_ADDR    varchar(200) DEFAULT 'OSINT',
    CFRT_GRD_CD    numeric(3) DEFAULT 4,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_OSINT_SITE_CLSTR_M.CLST_ID IS '클러스터아이디';
COMMENT ON COLUMN TB_OSINT_SITE_CLSTR_M.CLST_NM IS '클러스터명';
COMMENT ON COLUMN TB_OSINT_SITE_CLSTR_M.SIMHASH_6_4_VL IS '심해시64값';
COMMENT ON COLUMN TB_OSINT_SITE_CLSTR_M.OGNZ_MBER_CNT IS '조직구성원수';
COMMENT ON COLUMN TB_OSINT_SITE_CLSTR_M.RPRS_URL_ADDR IS '대표URL주소';
COMMENT ON COLUMN TB_OSINT_SITE_CLSTR_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_OSINT_SITE_CLSTR_M.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_OSINT_SITE_CLSTR_M.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_OSINT_SITE_CLSTR_M.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_OSINT_SITE_CLSTR_M.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_OSINT_SITE_CLSTR_M.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_OSINT_SITE_CLSTR_M IS 'OSINT사이트군집기본';

CREATE UNIQUE INDEX TB_OSINT_SITE_CLSTR_M_PK ON TB_OSINT_SITE_CLSTR_M
( CLST_ID );

ALTER TABLE TB_OSINT_SITE_CLSTR_M
 ADD CONSTRAINT TB_OSINT_SITE_CLSTR_M_PK PRIMARY KEY 
 USING INDEX TB_OSINT_SITE_CLSTR_M_PK;

-- ============================================================
-- 3.11 마약 도메인
-- 마약은어 및 거래 정보
-- ============================================================

-- 마약은어기본 테이블
CREATE TABLE TB_NCTC_SLANG_M
(
    SLANG_SN    BIGSERIAL NOT NULL,
    SLANG_WORD_NM    varchar(100) NOT NULL,
    NCTC_TYP_CD    varchar(20),
    NCTC_TYP_NM    varchar(100),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_NCTC_SLANG_M.SLANG_SN IS '은어일련번호';
COMMENT ON COLUMN TB_NCTC_SLANG_M.SLANG_WORD_NM IS '은어단어명';
COMMENT ON COLUMN TB_NCTC_SLANG_M.NCTC_TYP_CD IS '마약타입코드';
COMMENT ON COLUMN TB_NCTC_SLANG_M.NCTC_TYP_NM IS '마약타입명';
COMMENT ON COLUMN TB_NCTC_SLANG_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_NCTC_SLANG_M.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_NCTC_SLANG_M IS '마약은어기본';

CREATE UNIQUE INDEX TB_NCTC_SLANG_M_PK ON TB_NCTC_SLANG_M
( SLANG_SN );

ALTER TABLE TB_NCTC_SLANG_M
 ADD CONSTRAINT TB_NCTC_SLANG_M_PK PRIMARY KEY 
 USING INDEX TB_NCTC_SLANG_M_PK;

-- 마약거래내역 테이블
CREATE TABLE TB_NCTC_DLNG_T
(
    DLNG_SN    BIGSERIAL NOT NULL,
    DLNG_DT    timestamp with time zone,
    NCTC_TYP_CD    varchar(20),
    DLNG_AMT    numeric(15),
    PRCHR_ID    varchar(50),
    SLR_ID    varchar(50),
    PLFM_NM    varchar(100),
    INCDNT_NO    varchar(20),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_NCTC_DLNG_T.DLNG_SN IS '거래일련번호';
COMMENT ON COLUMN TB_NCTC_DLNG_T.DLNG_DT IS '거래일시';
COMMENT ON COLUMN TB_NCTC_DLNG_T.NCTC_TYP_CD IS '마약타입코드';
COMMENT ON COLUMN TB_NCTC_DLNG_T.DLNG_AMT IS '거래금액';
COMMENT ON COLUMN TB_NCTC_DLNG_T.PRCHR_ID IS '구매자아이디';
COMMENT ON COLUMN TB_NCTC_DLNG_T.SLR_ID IS '판매자아이디';
COMMENT ON COLUMN TB_NCTC_DLNG_T.PLFM_NM IS '플랫폼명';
COMMENT ON COLUMN TB_NCTC_DLNG_T.INCDNT_NO IS '사건번호';
COMMENT ON COLUMN TB_NCTC_DLNG_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_NCTC_DLNG_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_NCTC_DLNG_T IS '마약거래내역';

CREATE UNIQUE INDEX TB_NCTC_DLNG_T_PK ON TB_NCTC_DLNG_T
( DLNG_SN );

ALTER TABLE TB_NCTC_DLNG_T
 ADD CONSTRAINT TB_NCTC_DLNG_T_PK PRIMARY KEY 
 USING INDEX TB_NCTC_DLNG_T_PK;

-- ============================================================
-- 3.12 사기신고 도메인
-- 사기신고 및 지급정지
-- ============================================================

-- 사기피해자신고내역 테이블
CREATE TABLE TB_FRD_VCTM_DCLR_T
(
    DCLR_SN    BIGSERIAL NOT NULL,
    RCPT_DT    timestamp with time zone NOT NULL,
    RCPT_CHNL_CD    varchar(20) NOT NULL,
    VCTM_NM    varchar(150),
    VCTM_TELNO    varchar(11),
    CRIM_SE_CD    varchar(5),
    FRD_ACTNO    varchar(20),
    FRD_BANK_CD    varchar(10),
    DAM_AMT    numeric(15),
    INCDNT_OCRN_YMD    character(8),
    SMRY_CN    varchar(4000),
    PRGRS_STTS_CD    varchar(20) DEFAULT 'PENDING' NOT NULL,
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.DCLR_SN IS '신고일련번호';
COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.RCPT_DT IS '접수일시';
COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.RCPT_CHNL_CD IS '접수채널코드';
COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.VCTM_NM IS '피해자명';
COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.VCTM_TELNO IS '피해자전화번호';
COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.CRIM_SE_CD IS '범죄구분코드';
COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.FRD_ACTNO IS '사기계좌번호';
COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.FRD_BANK_CD IS '사기은행코드';
COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.DAM_AMT IS '피해금액';
COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.INCDNT_OCRN_YMD IS '사건발생일자';
COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.SMRY_CN IS '요약내용';
COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.PRGRS_STTS_CD IS '진행상태코드';
COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_FRD_VCTM_DCLR_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_FRD_VCTM_DCLR_T IS '사기피해자신고내역';

CREATE UNIQUE INDEX TB_FRD_VCTM_DCLR_T_PK ON TB_FRD_VCTM_DCLR_T
( DCLR_SN );

ALTER TABLE TB_FRD_VCTM_DCLR_T
 ADD CONSTRAINT TB_FRD_VCTM_DCLR_T_PK PRIMARY KEY 
 USING INDEX TB_FRD_VCTM_DCLR_T_PK;

-- 사기계좌지급정지내역 테이블 
CREATE TABLE TB_FRD_BACNT_SHTOT_T
(
    BACNT_SN    BIGSERIAL NOT NULL,
    ACTNO    varchar(20) NOT NULL,
    BANK_CD    varchar(30) NOT NULL,
    SHTOT_DT    timestamp with time zone NOT NULL,
    UNBLK_DT    timestamp with time zone,
    SHTOT_RSN_CD    varchar(20),
    INCDNT_NO    varchar(20),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_FRD_BACNT_SHTOT_T.BACNT_SN IS '계좌일련번호';
COMMENT ON COLUMN TB_FRD_BACNT_SHTOT_T.ACTNO IS '계좌번호';
COMMENT ON COLUMN TB_FRD_BACNT_SHTOT_T.BANK_CD IS '은행코드';
COMMENT ON COLUMN TB_FRD_BACNT_SHTOT_T.SHTOT_DT IS '차단일시';
COMMENT ON COLUMN TB_FRD_BACNT_SHTOT_T.UNBLK_DT IS '차단해제일시';
COMMENT ON COLUMN TB_FRD_BACNT_SHTOT_T.SHTOT_RSN_CD IS '차단사유코드';
COMMENT ON COLUMN TB_FRD_BACNT_SHTOT_T.INCDNT_NO IS '사건번호';
COMMENT ON COLUMN TB_FRD_BACNT_SHTOT_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_FRD_BACNT_SHTOT_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_FRD_BACNT_SHTOT_T IS '사기계좌차단내역';

CREATE UNIQUE INDEX TB_FRD_BACNT_SHTOT_T_PK ON TB_FRD_BACNT_SHTOT_T
( BACNT_SN );

ALTER TABLE TB_FRD_BACNT_SHTOT_T
 ADD CONSTRAINT TB_FRD_BACNT_SHTOT_T_PK PRIMARY KEY 
 USING INDEX TB_FRD_BACNT_SHTOT_T_PK;

-- ============================================================
-- 3.13 엔티티 해소 도메인
-- 동일인물 해소 및 충돌 관리
-- ============================================================

-- 동일인물해소내역 테이블
CREATE TABLE TB_SAME_PRSN_RSLV_T
(
    M_ATCH_SN    BIGSERIAL NOT NULL,
    CRTR_PRSN_ID    varchar(2000) NOT NULL,
    COMP_PRSN_ID    varchar(2000) NOT NULL,
    MTCHG_SCR    numeric(10) NOT NULL,
    MTCHG_CRTR_CD    varchar(20) NOT NULL,
    RVW_PRGRS_STTS_CD    varchar(20) DEFAULT 'PENDING' NOT NULL,
    AUTO_YN    character(1) DEFAULT 'Y' NOT NULL,
    RVWR_ID    varchar(50),
    RVW_YMD    character(8),
    RVW_OPIN_CN    varchar(4000),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_SAME_PRSN_RSLV_T.M_ATCH_SN IS '미터첨부일련번호';
COMMENT ON COLUMN TB_SAME_PRSN_RSLV_T.CRTR_PRSN_ID IS '기준인물아이디';
COMMENT ON COLUMN TB_SAME_PRSN_RSLV_T.COMP_PRSN_ID IS '비교인물아이디';
COMMENT ON COLUMN TB_SAME_PRSN_RSLV_T.MTCHG_SCR IS '매칭점수';
COMMENT ON COLUMN TB_SAME_PRSN_RSLV_T.MTCHG_CRTR_CD IS '매칭기준코드';
COMMENT ON COLUMN TB_SAME_PRSN_RSLV_T.RVW_PRGRS_STTS_CD IS '검토진행상태코드';
COMMENT ON COLUMN TB_SAME_PRSN_RSLV_T.AUTO_YN IS '자동여부';
COMMENT ON COLUMN TB_SAME_PRSN_RSLV_T.RVWR_ID IS '검토자아이디';
COMMENT ON COLUMN TB_SAME_PRSN_RSLV_T.RVW_YMD IS '검토일자';
COMMENT ON COLUMN TB_SAME_PRSN_RSLV_T.RVW_OPIN_CN IS '검토소견내용';
COMMENT ON COLUMN TB_SAME_PRSN_RSLV_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_SAME_PRSN_RSLV_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_SAME_PRSN_RSLV_T IS '동일인물해소내역';

CREATE UNIQUE INDEX TB_SAME_PRSN_RSLV_T_PK ON TB_SAME_PRSN_RSLV_T
( M_ATCH_SN );

ALTER TABLE TB_SAME_PRSN_RSLV_T
 ADD CONSTRAINT TB_SAME_PRSN_RSLV_T_PK PRIMARY KEY 
 USING INDEX TB_SAME_PRSN_RSLV_T_PK;

-- 충돌정보내역 테이블
CREATE TABLE TB_CRSH_INFO_T
(
    CRSH_SN    BIGSERIAL NOT NULL,
    CRTR_PRSN_ID    varchar(2000) NOT NULL,
    COMP_PRSN_ID    varchar(2000) NOT NULL,
    CRSH_FILD_NM    varchar(100),
    CRSH_DTL_CN    varchar(500),
    CRSH_TYP_CD    varchar(20),
    RESLV_YN    character(1) DEFAULT 'N',
    RESLV_PSN_ID    varchar(50),
    RSLV_YMD    character(8),
    SRC_ID    varchar(200),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_CRSH_INFO_T.CRSH_SN IS '충돌일련번호';
COMMENT ON COLUMN TB_CRSH_INFO_T.CRTR_PRSN_ID IS '기준인물아이디';
COMMENT ON COLUMN TB_CRSH_INFO_T.COMP_PRSN_ID IS '비교인물아이디';
COMMENT ON COLUMN TB_CRSH_INFO_T.CRSH_FILD_NM IS '충돌필드명';
COMMENT ON COLUMN TB_CRSH_INFO_T.CRSH_DTL_CN IS '충돌상세내용';
COMMENT ON COLUMN TB_CRSH_INFO_T.CRSH_TYP_CD IS '충돌타입코드';
COMMENT ON COLUMN TB_CRSH_INFO_T.RESLV_YN IS '해결여부';
COMMENT ON COLUMN TB_CRSH_INFO_T.RESLV_PSN_ID IS '해결사람아이디';
COMMENT ON COLUMN TB_CRSH_INFO_T.RSLV_YMD IS '해소일자';
COMMENT ON COLUMN TB_CRSH_INFO_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_CRSH_INFO_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_CRSH_INFO_T IS '충돌정보내역';

CREATE UNIQUE INDEX TB_CRSH_INFO_T_PK ON TB_CRSH_INFO_T
( CRSH_SN );

ALTER TABLE TB_CRSH_INFO_T
 ADD CONSTRAINT TB_CRSH_INFO_T_PK PRIMARY KEY 
 USING INDEX TB_CRSH_INFO_T_PK;

-- ============================================================
-- 3.14 공통코드 도메인
-- 참조 코드 관리
-- ============================================================

-- 공통코드 테이블
CREATE TABLE TB_COM_C
(
    CD_GRP_ID    varchar(200) NOT NULL,
    CD_VL    varchar(1000) NOT NULL,
    CD_NM    varchar(100) NOT NULL,
    CD_ENG_NM    varchar(256),
    SORT_SEQ    numeric(10) DEFAULT 0,
    USE_YN    character(1) DEFAULT 'Y' NOT NULL,
    RMRK_CN    varchar(4000)
);

COMMENT ON COLUMN TB_COM_C.CD_GRP_ID IS '코드단체아이디';
COMMENT ON COLUMN TB_COM_C.CD_VL IS '코드값';
COMMENT ON COLUMN TB_COM_C.CD_NM IS '코드명';
COMMENT ON COLUMN TB_COM_C.CD_ENG_NM IS '코드영문명';
COMMENT ON COLUMN TB_COM_C.SORT_SEQ IS '정렬순서';
COMMENT ON COLUMN TB_COM_C.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_COM_C.RMRK_CN IS '비고내용';

COMMENT ON TABLE TB_COM_C IS '공통코드';

CREATE UNIQUE INDEX TB_COM_C_PK ON TB_COM_C
( CD_GRP_ID,CD_VL );

ALTER TABLE TB_COM_C
 ADD CONSTRAINT TB_COM_C_PK PRIMARY KEY 
 USING INDEX TB_COM_C_PK;

-- 은행코드 테이블
CREATE TABLE TB_BANK_C
(
    BANK_CD    varchar(30) NOT NULL,
    BANK_NM    varchar(100) NOT NULL,
    ENG_NM    varchar(100),
    BANK_TYP_CD    varchar(20),
    USE_YN    character(1) DEFAULT 'Y' NOT NULL
);

COMMENT ON COLUMN TB_BANK_C.BANK_CD IS '은행코드';
COMMENT ON COLUMN TB_BANK_C.BANK_NM IS '은행명';
COMMENT ON COLUMN TB_BANK_C.ENG_NM IS '영문명';
COMMENT ON COLUMN TB_BANK_C.BANK_TYP_CD IS '은행타입코드';
COMMENT ON COLUMN TB_BANK_C.USE_YN IS '사용여부';

COMMENT ON TABLE TB_BANK_C IS '은행코드';

CREATE UNIQUE INDEX TB_BANK_C_PK ON TB_BANK_C
( BANK_CD );

ALTER TABLE TB_BANK_C
 ADD CONSTRAINT TB_BANK_C_PK PRIMARY KEY 
 USING INDEX TB_BANK_C_PK;

-- ============================================================
-- 3.15 Phase 6E 객체 마스터 도메인
-- 범죄 캠페인 군집 및 객체 마스터
-- ============================================================

-- 범죄캠페인군집기본 테이블
CREATE TABLE TB_CRIM_CMPGN_CLSTR_M
(
    CLST_ID    varchar(50) NOT NULL,
    CMPGN_NM    varchar(300),
    THRN_LVL_CD    varchar(20),
    BGNG_DT    timestamp with time zone,
    END_DT    timestamp with time zone,
    OGNZ_MBER_CNT    numeric(4) DEFAULT 0,
    SRC_ID    varchar(200),
    SRC_DMN_ADDR    varchar(200) DEFAULT 'KICS',
    CFRT_GRD_CD    numeric(3) DEFAULT 2,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_CRIM_CMPGN_CLSTR_M.CLST_ID IS '클러스터아이디';
COMMENT ON COLUMN TB_CRIM_CMPGN_CLSTR_M.CMPGN_NM IS '캠페인명';
COMMENT ON COLUMN TB_CRIM_CMPGN_CLSTR_M.THRN_LVL_CD IS '위협수준코드';
COMMENT ON COLUMN TB_CRIM_CMPGN_CLSTR_M.BGNG_DT IS '시작일시';
COMMENT ON COLUMN TB_CRIM_CMPGN_CLSTR_M.END_DT IS '종료일시';
COMMENT ON COLUMN TB_CRIM_CMPGN_CLSTR_M.OGNZ_MBER_CNT IS '조직구성원수';
COMMENT ON COLUMN TB_CRIM_CMPGN_CLSTR_M.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_CRIM_CMPGN_CLSTR_M.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_CRIM_CMPGN_CLSTR_M.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_CRIM_CMPGN_CLSTR_M.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_CRIM_CMPGN_CLSTR_M.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_CRIM_CMPGN_CLSTR_M.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_CRIM_CMPGN_CLSTR_M IS '범죄캠페인군집기본';

CREATE UNIQUE INDEX TB_CRIM_CMPGN_CLSTR_M_PK ON TB_CRIM_CMPGN_CLSTR_M
( CLST_ID );

ALTER TABLE TB_CRIM_CMPGN_CLSTR_M
 ADD CONSTRAINT TB_CRIM_CMPGN_CLSTR_M_PK PRIMARY KEY 
 USING INDEX TB_CRIM_CMPGN_CLSTR_M_PK;

-- ============================================================
-- 3.16 사칭 관계 도메인
-- 사칭(Fraud-as-a-Service) 이벤트
-- ============================================================

-- 사칭이벤트내역 테이블
CREATE TABLE TB_FAAS_EVT_T
(
    EVT_ID    varchar(50) NOT NULL,
    CLCT_MTHD_CD    varchar(20),
    PSDNM_VL    varchar(100),
    SCRIPT_TYP_NM    varchar(100),
    BGNG_DT    timestamp with time zone,
    END_DT    timestamp with time zone,
    CFRT    numeric(5,3) DEFAULT 1.000,
    VRFC_YN    character(1) DEFAULT 'Y',
    SRC_ID    varchar(200) NOT NULL,
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SRC_DMN_ADDR    varchar(200),
    CFRT_GRD_CD    numeric(3) DEFAULT 3,
    CLCT_DT    timestamp with time zone,
    RCRD_CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    RCRD_MDFCN_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN TB_FAAS_EVT_T.EVT_ID IS '이벤트아이디';
COMMENT ON COLUMN TB_FAAS_EVT_T.CLCT_MTHD_CD IS '수집방법코드';
COMMENT ON COLUMN TB_FAAS_EVT_T.PSDNM_VL IS '가명값';
COMMENT ON COLUMN TB_FAAS_EVT_T.SCRIPT_TYP_NM IS '스크립트타입명';
COMMENT ON COLUMN TB_FAAS_EVT_T.BGNG_DT IS '시작일시';
COMMENT ON COLUMN TB_FAAS_EVT_T.END_DT IS '종료일시';
COMMENT ON COLUMN TB_FAAS_EVT_T.CFRT IS '신뢰도';
COMMENT ON COLUMN TB_FAAS_EVT_T.VRFC_YN IS '검증여부';
COMMENT ON COLUMN TB_FAAS_EVT_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_FAAS_EVT_T.CRT_DT IS '생성일시';
COMMENT ON COLUMN TB_FAAS_EVT_T.SRC_DMN_ADDR IS '출처도메인주소';
COMMENT ON COLUMN TB_FAAS_EVT_T.CFRT_GRD_CD IS '신뢰도등급코드';
COMMENT ON COLUMN TB_FAAS_EVT_T.CLCT_DT IS '수집일시';
COMMENT ON COLUMN TB_FAAS_EVT_T.RCRD_CRT_DT IS '레코드생성일시';
COMMENT ON COLUMN TB_FAAS_EVT_T.RCRD_MDFCN_DT IS '레코드수정일시';

COMMENT ON TABLE TB_FAAS_EVT_T IS '사칭이벤트내역';

CREATE UNIQUE INDEX TB_FAAS_EVT_T_PK ON TB_FAAS_EVT_T
( EVT_ID );

ALTER TABLE TB_FAAS_EVT_T
 ADD CONSTRAINT TB_FAAS_EVT_T_PK PRIMARY KEY 
 USING INDEX TB_FAAS_EVT_T_PK;

-- ============================================================
-- 부가 확장 도메인 (V4 확장)
-- ============================================================

-- 가상자산지갑위험내역 테이블
CREATE TABLE TB_VR_AST_WLET_RISK_T
(
    RPTP_SN    BIGSERIAL NOT NULL,
    WLET_ADDR    varchar(200) NOT NULL,
    BLCKCHN_NM    varchar(20) NOT NULL,
    SRC_ID    varchar(200) NOT NULL,
    INQ_DT    timestamp with time zone NOT NULL,
    RISK_SCR    numeric(5,2),
    RISK_TYP_CD    varchar(20),
    KYC_VRFC_YN    character(1) DEFAULT 'N',
    DLNG_NOCS    numeric(10),
    RAW_JSON_CN    varchar(4000),
    CRT_DT    timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TB_VR_AST_WLET_RISK_T.RPTP_SN IS '보고서일련번호';
COMMENT ON COLUMN TB_VR_AST_WLET_RISK_T.WLET_ADDR IS '지갑주소';
COMMENT ON COLUMN TB_VR_AST_WLET_RISK_T.BLCKCHN_NM IS '블록체인명';
COMMENT ON COLUMN TB_VR_AST_WLET_RISK_T.SRC_ID IS '출처아이디';
COMMENT ON COLUMN TB_VR_AST_WLET_RISK_T.INQ_DT IS '조회일시';
COMMENT ON COLUMN TB_VR_AST_WLET_RISK_T.RISK_SCR IS '위험점수';
COMMENT ON COLUMN TB_VR_AST_WLET_RISK_T.RISK_TYP_CD IS '위험타입코드';
COMMENT ON COLUMN TB_VR_AST_WLET_RISK_T.KYC_VRFC_YN IS 'KYC검증여부';
COMMENT ON COLUMN TB_VR_AST_WLET_RISK_T.DLNG_NOCS IS '거래건수';
COMMENT ON COLUMN TB_VR_AST_WLET_RISK_T.RAW_JSON_CN IS '원시JSON내용';
COMMENT ON COLUMN TB_VR_AST_WLET_RISK_T.CRT_DT IS '생성일시';

COMMENT ON TABLE TB_VR_AST_WLET_RISK_T IS '가상자산지갑위험내역';

CREATE UNIQUE INDEX TB_VR_AST_WLET_RISK_T_PK ON TB_VR_AST_WLET_RISK_T
( RPTP_SN );

ALTER TABLE TB_VR_AST_WLET_RISK_T
 ADD CONSTRAINT TB_VR_AST_WLET_RISK_T_PK PRIMARY KEY 
 USING INDEX TB_VR_AST_WLET_RISK_T_PK;


-- ============================================================
-- ============================================================